import React, { useState, useRef, useEffect } from 'react';
import { ChevronDown } from 'lucide-react';

interface JobSearchDropdownProps {
  value: string;
  onChange: (value: string) => void;
  onBlur?: () => void;
  placeholder?: string;
  className?: string;
}

const JOB_OPTIONS = [
"Software Engineer" "Frontend Developer" "Backend Developer" "Full Stack Developer" "Mobile App Developer" "Web Developer" "UI Designer" "UX Designer" "Data Scientist" "Machine Learning Engineer" "AI Researcher" "Cloud Architect" "Devops Engineer" "Systems Administrator" "Network Engineer" "Database Administrator" "Cybersecurity Analyst" "QA Engineer" "Game Developer" "Embedded Systems Engineer"
"Technical Writer" "Product Manager" "Scrum Master" "IT Support Specialist" "Help Desk Technician" "Doctor" "Nurse" "Licensed Practical Nurse" "Certified Nursing Assistant" "Pharmacist" "Pharmacy Technician" "Paramedic" "Emergency Medical Technician" "Dentist" "Dental Hygienist" "Dental Assistant" "Veterinarian" "Veterinary Technician" "Physical Therapist" "Occupational Therapist"
"Radiologic Technologist" "Medical Assistant" "Surgical Technologist" "Respiratory Therapist" "Home Health Aide" "Barista" "Server" "Cook" "Line Cook" "Prep Cook" "Sous Chef" "Chef" "Pastry Chef" "Food Service Worker" "Waiter" "Waitress" "Host" "Hostess" "Busser" "Dishwasher"
"Caterer" "Food Runner" "Fast Food Worker" "Drive Thru Operator" "Bartender" "Barback" "Delivery Driver" "Pizza Delivery Driver" "Hotel Housekeeper" "Front Desk Clerk" "Hotel Concierge" "Bellhop" "Room Service Attendant" "Valet Attendant" "Casino Dealer" "Casino Host" "Event Coordinator" "Wedding Planner" "Banquet Server" "Club Promoter"
"Tour Guide" "Cashier" "Retail Associate" "Sales Associate" "Stock Associate" "Customer Service Representative" "Customer Service" "Inventory Clerk" "Shelf Stocker" "Store Manager" "Assistant Store Manager" "Greeter" "Bagging Clerk" "Mall Security Guard" "Merchandiser" "Personal Shopper" "Gift Wrapper" "Loss Prevention Specialist" "Taxi Driver" "Ride Share Driver"
"Driver" "Bus Driver" "School Bus Driver" "Truck Driver" "Courier" "Bicycle Messenger" "Forklift Operator" "Warehouse Worker" "Order Picker" "Package Handler" "Logistics Coordinator" "Dock Worker" "Shipping Clerk" "Nanny" "Babysitter" "Daycare Worker" "Preschool Teacher" "Childcare Assistant" "Elder Caregiver" "Housekeeper"
"Cleaner" "Janitor" "Maid" "Pet Sitter" "Dog Walker" "Pet Groomer" "Landscaper" "Gardener" "Pool Cleaner" "Electrician" "Plumber" "Carpenter" "Welder" "Hvac Technician" "Auto Mechanic" "Diesel Mechanic" "Machinist" "Construction Worker" "General Laborer" "Roofing Specialist"
"Painter" "Drywall Installer" "Flooring Installer" "Bricklayer" "Receptionist" "Administrative Assistant" "Office Clerk" "Data Entry Clerk" "File Clerk" "Executive Assistant" "Secretary" "Office Manager" "Virtual Assistant" "Call Center Representative" "Collections Agent" "Telemarketer" "Appointment Setter" "Mailroom Clerk" "Switchboard Operator" "Accountant"
"Auditor" "Bookkeeper" "Tax Preparer" "Financial Analyst" "Budget Analyst" "Loan Officer" "Insurance Agent" "Claims Adjuster" "Bank Teller" "Mortgage Broker" "Investment Analyst" "Payroll Specialist" "Real Estate Agent" "Property Manager" "Teacher" "Teaching Assistant" "Substitute Teacher" "School Counselor" "Principal" "Tutor"
"Librarian" "Library Assistant" "Academic Advisor" "Professor" "Lawyer" "Paralegal" "Legal Assistant" "Court Clerk" "Judge" "Security Guard" "Private Investigator" "Police Officer" "Corrections Officer" "Firefighter" "Manager" "Assistant Manager" "Shift Leader" "Supervisor" "Team Lead" "Freelance Writer"
"Graphic Designer" "Illustrator" "Photographer" "Video Editor" "Voice Actor" "Music Producer" "Social Media Influencer" "Virtual Tutor" "Translator" "Maintenance Worker" "Facilities Technician" "Groundskeeper" "Building Superintendent" "Handyman" "Lifeguard" "Camp Counselor" "Amusement Park Worker" "Theme Park Attendant" "Carnival Worker" "Tour Bus Driver"
"Street Performer" "Festival Staff" "Farm Worker" "Fruit Picker" "City Planner" "Urban Planner" "Building Inspector" "City Clerk" "City Council Member" "Mayor's Assistant" "Public Works Laborer" "Water Treatment Plant Operator" "Waste Management Worker" "Sanitation Worker" "Street Sweeper Operator" "Parking Enforcement Officer" "Meter Reader" "Building Maintenance Worker" "Parks And Recreation Worker" "Recreation Coordinator"
"Community Outreach Specialist" "City Bus Driver" "Transit Operator" "Traffic Engineer" "Civil Engineer (municipal)" "City Electrician" "Zoning Officer" "Public Safety Officer" "Emergency Management Coordinator" "City Attorney" "Planning And Zoning Coordinator" "City Engineer" "City Project Manager" "Permit Technician" "Code Enforcement Officer" "Neighborhood Services Coordinator" "City Grant Writer" "Community Development Specialist" "Animal Control Officer" "Public Health Inspector"
"City Auditor" "Budget Officer" "City Finance Director" "Environmental Compliance Specialist" "City Surveyor" "Municipal Court Clerk" "Recycling Program Coordinator" "Water Quality Technician" "Traffic Signal Technician" "Road Maintenance Worker" "City Arborist" "Crew Member" "Associate" "Team Member" "Helper" "Laborer" "Worker" "Staff Member" "General Worker" "Operator"
"Technician" "Specialist" "Coordinator" "Agent" "Assistant" "Personal Trainer" "Psychiatrist" "" "Cuny Broadcast Associate" "Secretary OF Commissioner" "Captain Detailed AS Chief OF Crime Control Strategies" "Bike Tech / Specialist" "Associate Retirement Benefits Examiner" "Concessions / Attendant" "Associate Counsel" "Supervising Inspector General" "Prep / Smoked Fish" "Director OF Technology Development PD" "Admin JOB Opor Spec Managerial" "Heating Plant Technician"
"Teacher Special ED" "Assistant Commissioner FOR Labor Relations & Admin" "Agency Chief Decarbonization Officer" "Custodial Supervisor" "Usher / Concessions / Box Office" "Customer Service / Counter Rep" "Agency Attorney Dc37" "Mechanical Engineer" "*community Liaison Worker" "Health Services Manager NON Managerial Level I" "Secretary TO THE Chairperson" "Deputy Director OF Admin Worker's Comp Benefits" "Adult Educator Assistant Coord" "Homemaker" "Executive Assistant TO THE Director OF Management & Budget" "Lot Manager" "Lead Attendant" "Director OF THE City Record" "Director OF Public Health Emergency Evaluation" "Instrumental Specialist"
"City Dentist" "Supervising FM MGL Det: Chief OF Staff TO Fire Comm" "Maintenance Technician / Handyman" "Concessions / Food Runner" "Safety Specialist" "House Manager" "Deputy City Clerk" "Chief Clerk" "Pension Investment Advisor" "Confidential Secretary" "Personal Banker" "Senior Bookseller" "Machinist's Helper" "Traffic Control Inspector" "Temporary Clerk" "Cook / Dumpling Maker" "Distinguished Professor" "Marine Oiler" "Executive Assistant TO THE Chancellor" "School Psychologist"
"Executive Secretary TO THE Public Advocate" "Cook / Line" "Health Care Prog Plan/analyst" "Adult ED 30 H" "Adult Education Teacher" "Public Health Epidemiologist" "Senior Vice President" "City Deputy Medical Director" "Dean" "Education Facilitator" "Director OF HUD Acquired Properties" "Assistant TO Deputy Comptroller" "Customer Service / Personal Banker" "Executive Agency Counsel" "Claim Specialist" "Deputy Administrator/comsnr DOS" "Pickup / Delivery Driver" "Assistant Executive Director" "Glazier" "Program Officer"
"Administrative Supervisor OF Skilled Trades" "Assistant District Manager" "Supervisor OF Housing Caretaker" "Executive Secretary TO City Clerk" "Director OF THE Office FOR People With Disabilities" "Traffic Enforc Agent L 3 & 4 Only" "Valet (base)" "Deputy Superintendent" "Associate Labor Relations Analyst" "Director OF Psychological Services" "Housing Manager" "Mariner" "Assistant Commissioner FOR Aftercare & Preventive Svcs" "District Attorney" "Administrative Public Information Specialist" "Supervisor OF Ironwork" "Director OF Investigative Audits" "Supervisor Dockbuilder" "Evidence AND Property Control Specialist" "Food Service Manager"
"Administrative Space Analyst" "School Lunch Assistant" "Captain Managerial Details" "Assistant Commissioner FOR Program Development" "Apprentice" "Agency Attorney" "Research Liaison ADN Governmental Coordinator" "FOH Supervisor" "Director, Public Affairs AND Communication" "Teacher Aide" "F/T School Safety Officer" "Executive Director" "Secretary TO THE Excutive Assistant" "Chancellor" "Physician's Assistant" "Assistant Supervising Chief Surgeon" "Maker" "Ice Cream Maker / Batch Operator" "Home Aide" "Program Research Analyst TO THE Public Advocate"
"Kitchen / Prep Cook" "Shift Supervisor" "Attorney AT LAW" "Public Relations Adviser" "Store Associate" "Recreation Director" "Clip Instructor" "Legislative Intern" "Environmental Health Technician" "City Clinician" "Press Officer" "Senior Occupational Therapist" "Special Assistant TO THE Commissioner" "Secretary TO Executive Director" "Concessions Cashier" "Chaplain" "Chief OF Strategic Initiatives" "Key Holder / Lead" "Secretary TO THE Special Commissioner OF Investigation NYC" "*associate Education Officer"
"Telecommunication Manager" "DIR OF Mgnt System, Planning, Research AND Eval" "Exterminator" "Principal Legislative Financial Analyst" "Deputy Chief Surgeon" "Chief Information Technology Officer" "Director OF Office FOR People With Disabilities" "Supervisor Plasterer" "Director OF Criminal Justice Planning AND Policy Development" "Pizza Cook" "Human Rights Specialist" "DIR OF Healthcare Facilities AND Provider Readiness" "JR PH Nurse" "*attorney AT LAW" "Rubber Tire Repairer" "Certified Database Administrator" "Emergency Medical Specialist EMT" "Probation Assistant" "Shuttle Driver" "Executive Director, NEW York City Loft Board"
"School Safety Agent" "Assistant Commissioner" "EOC Mail/message Services Worker" "Administrator OF Medical Affairs" "Nycaps Process Analyst Manager" "Stenographic/secretarial Associate" "Security Staff" "Special Examiner" "Watershed Maintainer" "Health Services Manager" "Director, Research Development AND Policy Analysis" "12 Month Special Education Supervisor" "Telecommunications Associate" "Assistant Vice President" "High Pressure Plant Tender" "Assoc Supvr OF Schl SEC" "Financial Advisor" "Scooper / Crew" "Televison Equipment Operator" "Substitute Health Svc. Aide"
"School Neighborhood Worker" "University Associate Dean" "Supervisor II Social Work" "Repair Shop Manager" "Director OF Mortgage Research AND Analysis" "Mental Health Worker" "Restaurant Server" "Economist" "Adjunct Associate Professor" "Decedent Property Agent" "LAB Specialist/assistant" "Urban Park Ranger" "Surveyor" "Teacher Resource Room" "Deputy Director OF Management" "Principal Planning Consultant" "Director OF Exercises AND Training" "Special Assistant TO THE District Attorney" "Purchasing Agent" "Shift Lead / Supervisor"
"Supervising Computer Service Technician" "Secretary TO Dept Chancellor" "Commissioner" "Counsel TO Minority Leader" "Substitute School Aide" "Landmarks Preservationist" "Scooper/server" "Legislative Assistant" "Administrative Associate" "University Assistant Architect" "Admin JOB Opportunity Spec NM" "Communication Assistant" "Gasoline Roller Engineer" "Systems Administrator CAM FIN BD" "Chauffeur Attendant" "Assistant Commisioner" "Secretary TO THE First Assistant Corporation Counsel" "Buyer" "Secretary TO THE Chair" "EOC Custodial Assistant"
"Executive Director TO THE Environmental Control Board" "EOC Adjunct Lecturer" "Deputy Chief Technology Officer" "Furniture Maintainer" "Usher / Box Office / Concessions" "City Elevator Operator" "Administrative Manager" "Principal Nutrition Consultant" "Executive Assistant TO THE Deputy Commissioner" "Executive Assistant TO THE President OF THE TAX Commission" "Counsel TO THE Board" "School Equipment Maintainer" "Public Health Preventative Medicine Resident" "Elevator Mechanic Helper" "Monuments Officer" "Custodial Assistant" "Confidential Assistant TO THE Commissioner" "Coach / Instructor" "Program Coordinator" "Senior Accountant Investigator"
"City Assessor" "Insurance Advisor" "Confidential Examiner" "Emergency Medical Specialist Paramedic" "Director OF Admin" "Supervisor OF Nurses" "Associate Rehabilitation Specialist" "Legislative Project Manager" "Transportation Specialist" "SR Community Organization Specialist Urban Renewal" "Analyst (ib)" "Server / Bartender (tipped)" "Administrative Blasting Inspector" "Usher / Box Office" "Chemical Engineer" "Architect" "Special Assistant District Attorney" "Section Lead" "Supervising School Aide" "Executive Assistant TO THE City Clerk"
"Deputy Chief Information Technology Officer" "Mayoral Office Assistant" "Senior Field Supervisor" "Electricians Helper" "Director OF Council Services Bureau" "Associate Fire Protection Inspector" "Counter" "Senior Advisor TO THE Mayor" "Projectionist / AV" "Horseshoer" "Executive Assistant TO THE Commissioner OF Employment" "Benefits Opportunity Specialist" "Laboratory Helper" "Member OF THE Environmental Control Board Oath" "University Engineer" "Exec SEC TO Advisory BD FOR Locational AND Extension Educ" "Chief Diversity Officer Ýdoe¨" "District Manager" "Senior Registrar" "Usher / Seasonal Usher"
"Correction Officer" "Senior Repair Crew Chief" "Research Assistant Behav SCI" "College Security Specialist" "Administrative Director OF Residential Child Care" "Student Legal Specialist" "Legislative Systems Manager" "Research AND Liaison Specialist" "DIR OF Quality & Cost Control" "Assoc Spvr OF School Security" "Visitor Services Associate" "Certified Local Area Network Administrator" "Administrative Contract Specialist" "Executive Director, Technological Development" "City Research Scientist" "Dietitian" "Director OF EEO" "Supervisor III Social Work" "Legislative Computer Support Specialist" "Front Desk Agent"
"Director OF Community Programs" "Asst Project Planner" "Radio AND Tevevision Operator" "Assistant Principal Assigned" "Associate Laboratory Microbiologist" "Commissioner OF Department OF Veteran's Services" "Fraud Investigator" "Executive Chief OF Staff" "Associate Landmarks Preservationist" "Lot Associate" "Education Analyst Trainee" "PRE SES ED Para" "Chief OF Professional Standards" "Sorter" "Administrative Public Information Specialist NM Former M1/m2" "Senior Voting Machine Technician" "Forensic Mortuary Technician" "Printing Press Operator" "Senior Executive Secretary" "Director OF THE Mayor�s Office OF Administrative Services"
"Senior Director Collections" "Laboratory Associate" "Distinguished Lecturer" "Director OF Community Participation Programs" "Assist Coordinating Manager" "Marine Engineer" "Secretary TO THE Special Commissioner Investigation NYC SCH" "Medical Director" "School Secretary" "Investigator Empl Disc" "City Medical Examiner" "Electrical Engineer" "Director OF Audit AND Investigation" "City Medical Director" "Director OF Social & Community Services" "Associate Correctional Counselor" "Retail Sales Associate" "Valet Attendant (w/ Tips Typical Total)" "Special Advisor TO THE City Clerk" "Chief Strategy Officer/division Ýdoe¨"
"Associate Real Property Manager" "Deputy Chief OF Staff TO THE Chancellor Ýdoe¨" "Local Instructional Supervisor" "SR College Laboratory Tech" "JOB Training Participant" "Server / Front Of House" "Administrative Printing Services Manager" "Jewelry Specialist" "Highway Transportation Specialist" "Box Office / Ticket Seller" "City Collector" "Labor Relations Analyst Trainee" "Events / PR" "Employee Health Benefits Program Director" "Secretary TO Community School Board" "Senior College LAB Tech" "Senior Management Consultant" "Assistant Comptroller" "Assistant Principal Custodial Supervisor" "Youth Coordinator"
"Third Assistant Marine Engineer" "Assistant Legislative Representative" "Investigator" "Grocery Stocker" "Water Treatment Plant Operator L2 & 3" "NEW York City Public Service Fellow" "Assistant Comptroller OF IT" "Spa Specialist" "Assistant College Security Director" "Director OF THE Office OF Criminal Justice" "Quality Assurance Specialist" "Catering / Production Support" "Administrator Supt Campus B/G" "Secretary OF Department" "Automotive Service Worker" "Supervisor PER Session" "Secretary TO THE Exec Deputy Commissioner" "Stenographer TO THE Corporation Counsel" "Stock Worker" "Deckhand"
"Deputy Director OF Security" "Associate Director, Office OF Neighborhood Safety" "Captain Detailed AS Chief OF Organized Crime Control" "Revenue Auditor / Cash Office" "EOC Lecturer" "Construction Project Manager Intern" "Admin Tests & Meas Spec" "Assistant Advocate" "Civil Engineering Intern" "Police Officer, Special Assignment" "Actuarial Specialist Level II, OJ" "Actuarial Specialist Level I" "Commissioner OF Children's Services" "Deputy Director OF Cyber Crime Forensics" "*agency Attorney" "Warden Assistant Deputy Warden" "Director OF Program Planning" "Director,citywide Occupational Safety & Health Program" "Secretary OF THE TAX Commission" "Hotel Manager (annual)"
"Administrative Investigator" "Foster Grandparent" "Deputy Assistant Counsel" "Secretary TO Commissioner" "Instructor / Coach" "Cuny Custodial Assistant" "Dockmaster" "Director OF Design" "Director, Data Processing Coordination" "Supervisor Highway Repairer" "Child AND Family Specialist" "Director OF Technical Services" "Administrative Project Director" "Assistant TO THE President" "Mortgage / Loan Officer" "Senior Legislative Investigator" "Nurse's Aide" "Physicist" "Assistant Superintendent OF Schools" "Consulting Engineer"
"General / Store Manager" "Secy TO THE Director OF Collective Bargaining" "*admin Schl Secur MGR MGL" "Pizza Cook / Oven Operator" "Teacher Special Education" "Architectural Intern" "City Veterinarian" "Criminalist Assistant Director OF Laboratory" "Admin Construction Project Manager" "Teller / Bank Associate" "Spvsg FAD DIR Dsptch OP Detail" "Campus Public Safety Sergeant" "Legistative Manager Office OF Communication" "Assistant Budget Analyst" "Fiscal AND Policy Analyst" "City Debris Remover" "Assistant Deputy Commissioner SS" "Captain Detailed AS Chief OF Labor Relations" "General Counsel" "Director Legal Division/gen Counsel& Spec Counsel"
"Project Coordinator" "Chief Administrative Supt Campus B/G" "Assistant District Attorney" "City Chief Decarbonization Officer" "Deputy Asst Commissioner FOR Program DEV & Anal" "Executive Assistant FOR Programs & Policy" "Principal Administrative Associate LEV 1 & 2 NON Supvr" "Chair Landmarks Preservation Commission" "Hcppa" "Commiss OF THE OFF TO END Domest AND Gend BA Viol" "College Aide Assignment Levels II AND III" "Cuny Technical Support Aide" "SR Management Consultant" "Chief Administrator OF Impartial Hearing Office" "Ride / Park Tech" "Administrative Assistant TO THE Comptroller" "Supervising Blasting Inspector" "Deputy Commissioner" "Campus Peace Officer" "Front Of House Supervisor"
"IT Automation AND Monitoring Engineer" "Supervisor OF Traffic Device Maintainers L2 & L3" "Secretary TO THE Commissioner" "Deputy Public Administator" "Administrative Business Promotion Coordinator" "Custodian Engineer" "Equal Employment Opportunity Officer" "Pizza Cook / Maker" "Repair Crew Chief" "Senior Secretary" "Associate Park Service Worker" "Park Services Worker" "Administrative Chief" "Director OF Tenant & Community Affairs" "Service Team" "Public Relations Officer" "*certified Database Administrator" "Assistance Finance Officer" "School Secretary REG SUB" "Supervisor Ship Carpenter"
"Secretary OF THE Commission" "Fingerprint Technician Trainee" "Deputy Chief" "Financial Clerk" "Assistant Administrator" "Supervising Special Officer" "Director OF Labor Relations" "Surgeon" "Social Worker" "Commissioner OF Labor Relations" "County Detective" "Chief OF Student Pathways Ýdoe¨" "Assistant Director OF Legal Services" "Highways AND Sewers Inspector" "Research Projects Coord" "Teacher OF Library" "Housing Stock Worker" "Correction Administrative Aide" "Case Management Nurse" "Radio Repair Mechanic"
"EOC Accountant" "Investment Banking Analyst (entry)" "Butcher" "*associate Director Health Program" "Medicolegal Analyst" "Assistant Director OF Intergroup Relations" "Legislative Financial Analyst" "Bridge Operator" "12 Month Special Education Asst. Principal" "Associate Commissioner FOR Adult Services" "Executive Assistant TO THE Executive Deputy ADM" "Captain D/A Deputy Inspector" "Senior IT Architect" "Deputy Unit Chief" "Senior Mental Health Worker" "Supervising Dockmaster" "Chief College LAB Technician" "Director OF Purchase" "Special Investigator" "Authenticator / Specialist"
"Secretary TO THE Board OF Correction" "Transportation Inspector" "Communication Electrician" "Porter Supervisor (utility Worker Lead)" "Public Service Interne" "Deputy Community Superintendent" "EOC Assistant" "Kitchen Team" "Associate Urban Designer" "Licensed Barber" "Cheese Monger" "Chief OF Staff TO THE Deputy Chancellor Ýdoe¨" "Secretary TO Deputy Executive Director" "Director NYC Loft Board" "Laboratory Microbiologist" "University Professor" "Administrative Claim Examiner" "Chief Service Officer" "Regional Instructional Superintendent" "Child Protective Specialist"
"Registration Staff" "Administrative Architect" "Special Asst FOR Investigations/inspector GEN" "Executive Inspector" "Area Supervisor" "Supervising Emergency Medical Service Specialist" "Chief OF Housing Community Activities" "Chief OF Information Technology" "Exec Asst TO THE Deputy COM FOR Citywide Personnel Svcs Dcas" "Director OF Management Planning" "Director OF Independent Budget Office" "Personal Trainer / Instructor" "Investigator Trainee" "UFT School Secretary Assigned NON School Based 12 Month" "Special Assistant TO THE Fire Commissioner" "Congreg Care Spec ACS" "Teach Asst Vocation REG SUB" "Instrumental Specialist Trainee" "Public Records Officer" "Estimator"
"Administrative Nutritionist" "City Medical Specialist" "EOC Administrative Assistant" "Strategi Initiative Specialist" "Child Welfare Specialist" "Secretary TO THE Counsel TO THE Chancellor" "DIR OF Operations" "Police Officer D/A Detective 1ST GR" "Coordinator OF Veterans' Affairs" "*school Lunch Helper" "Chief OF Staff" "Staff Nurse" "Police Surgeon" "Soft Serve Attendant" "EOC Custodial Supervisor" "Executive Assistant TO Commissioner OF Transportation" "Administrative Housing Superintendent" "Health Services Manager NON Managerial Level II" "Fitting Room Attendant" "BIO Medical Equipment Technician"
"Emergency Preparedness Specialist" "Certified IT Administrator" "Office Assistant" "Housing Exterminator AL II & III" "Coop Trainee Typist" "Tech Associate" "Chief TAX Compliance Officer" "Senior Office Appliance Maintainer" "Special Assistant TO Commissioner" "Chief OF Staff Mayor's Office" "Captain" "City Pest Control Aide" "Fire Protection Inspector" "Front Desk / Reception" "Legal Coordinator" "Supervisor OF Office Machine Operations" "Associate Human Rights Specialist" "Director OF THE Mayor�s Office OF Appointments" "Assistant Commissioner OF Operations" "Manager OF Radio Repair Operations"
"Assist Commissioner FOR Intergovernmental Relations" "Principal Investment Officer" "Sign Language Interpreter 1,2,3 10M" "College Security Director" "Assistant Principal Admin" "Fire Medical Officer" "Secretary TO THE Executive Director" "Principal Appraiser" "IT Senior Associate" "Regional Director Mental Health Mental Retard & ALC Service" "Teacher Attendance" "Supervisor III" "General Superintendent" "Executive Legislative Secretary" "EOC Accounting Assistant" "Housing Consultant" "Supervisor OF Mechanics" "Pharmacy Tech" "Community Coordinator" "Lecturer/doctoral Schedule"
"Dietary Aide" "Public Health/preventive Medicine Resident" "Clinical Professor" "Fitness Instructor" "Supvsng Systems Analyst" "Sheet Metal Worker" "Director OF Public Affairs" "Director, NYC ART Commission" "Special Assistant TO Deputy Executive Director" "Police Officer D/A Detective 2ND GR" "Capt DET CHF Spec Operations M" "NON Teaching Adjunct IV" "Senior Supervisor Communication Electrician" "Senior General Deputy Manager" "Coordinating Manager" "*certified Local Area Network Administrator" "Field Investigation Specialist" "Secretary TO THE Chancellor" "Exec Director OF Grants Management AND Administration" "Director OF Research Planning AND Policy Analysis"
"Computer Service Technician" "Food Service Administrator" "Computer Associate" "Summer College Intern" "Attendant / Cashier" "Associate Operations Communications Specialist" "Director OF Interagency Planning" "Legislative Aide" "Director OF City Legislative Affairs" "NON Teaching Adjunct V" "Asbestos Handler" "Adjunct College LAB Tech" "Captain D/A Chief OF Management Analysis AND Planning" "Executive Director OF Standards AND Appeals" "Marine Maintenance Mechanic" "Supervising Hull & Machinery Inspector" "Server/operator" "First Assistant TO THE Public Advocate" "Substance Abuse Prevention & Intervention Specialist" "Director, Medical Affairs"
"Supervisor Carpenter" "Director OF Bureau OF Consumer Services" "Lot Attendant / Cashier" "Resident Building Superintendent" "Telecommuncation Manager" "ADM Manager NON MGR" "Consultant" "Assistant Resident Building Supt" "Commissioner OF Buildings" "Supervisor OF Bridge Operations" "Principal Multiple Dwelling Specialist" "Executive Assistant TO THE Chairman" "Principal School Neighborhood Worker" "Director OF Internal Affairs PD" "Administrative Public Health Sanitarian" "Urban Archeologist" "Psychiatrist (emergency Dept.)" "IT Security Specialist" "Assistant Sergeant AT Arms" "Transportation Borough Commissioner"
"Assist Commissioner" "DEP DIR OF Program Planning" "Guidance Counselor" "Educational Administrator" "Director OF Planning" "Key Holder / Senior Sales" "Associate Youth Development Specialist" "Confidential Investigator" "Secretary TO THE Fire Commissioner" "Traffic Enforc Agent" "Supervisor Glazier" "*adm School Security Manager U" "Calendar Assistant" "Attorney Campaign FIN Board" "Associate Contract Specialist" "Fire Cadet" "Principal Administrative Associate" "Appraiser" "Information Systems Aide" "Deputy Assistant Commissioner"
"Director OF Neighborhood Conservation" "Deputy Director OF Management & Budget" "Director OF Motor Equipment" "Director OF Neighborhood Park Restoration" "Director OF Puppetry" "Maintenance / Janitorial" "IT Infrastructure Engineer" "Assistant Media Services Technican" "Captain Chief OF Staff" "*elevator Operator" "Media Services Technician" "Congreg Care Spec DJJ" "Executive Assistant TO THE Director" "Guest Services / Front Desk" "Deputy Chief OF Operations" "Director OF Contract Administration" "Supervising Rackets Investigator" "DIR Policy Econom Resrch" "Rackets Investigator Start >4 24 08 NO ABC" "City Seasonal Aide"
"Associate (ib)" "Director OF Urban Archaeology" "P/T School Aide" "Human Resources Administrator" "*coordinating Manager" "Deputy Commissioner FOR City Personnel Services" "Asst Commissioner FOR Planning & Program DEV" "DIR OF Investigative Acctng AND Economic Crimes Invstngs" "Finance Officer" "Supervising Deputy Sheriff AL 1 Only 40 HR" "Sign Language Interpreter" "Client Service / Operations" "Store / Ops Manager" "Director FOR Equal Employment Opportunity" "Public Advocate" "Business Promotion Coordinator" "Cuny Start Instructor" "Mayor" "Senior Executive Director OF Intergovernmental Affairs Ýdoe¨" "First Deputy Mayor"
"Assistant Purchasing Agent" "*watchperson" "Inspector Plumbing" "Fiscal & Policy Analyst" "Arts Program Specialist" "Dishwasher / Kitchen Help" "Motor Vehicle Supervisor" "Facility Supervisor" "Server (restaurant)" "EOC Higher Education Associate" "Front Desk Manager" "Legal Secretarial Assistant AL 2,3,4 Only" "P.o. DET Spec" "Gelato Maker / Artisan" "Deputy Director" "Investment Manager" "Director OF Legislative Coordination" "Assistant Administrator OF Public Affairs" "Teller" "Rackets Investigator"
"Cyber Security Analyst" "Industrial Hygienist" "Education Officer" "Probation Adjunct Trainer" "Superintendent OF Adult Institutions" "Front Desk / Member Services" "Deputy Administrator" "Mortgage Loan Officer" "Director OF Information AND Research" "City Clerk & Clerk OF Council" "Secretary TO THE First Deputy Commissioner" "DIR OF Audit & Prog Analysis" "Confidential Assistant TO THE Comptroller" "Commissioner OF Sanitation" "Lieutenant D/A Special Assignment" "Secretary TO THE Human Resources Administrator" "Business Research & Data Analytics Specialist" "Counter/cashier / Takeaway" "Confidential Asst TO THE Executive DIR" "Associate AIR Pollution Inspr"
"SR Associate Health Program Director" "Educational Management Associate" "Principal Administrative Associate NON Supvr" "Deputy Executive Director OF Business AND Administration" "Confidential Secy" "Cleaner / Janitor" "Deputy Executive Director" "Lieutenant D/A Commander OF Detective Squad" "Pizza Maker / Cook" "Landscape Architect" "Deputy Auditor General" "Computer Programmer Analyst Trainee" "Assistant Electrical Engineer" "Warden Deputy Warden" "NEW Principal Intern" "EOC Adjunct College LAB Tech" "Assistant Director Health Program" "Special Asst TO Exec DIR" "Deputy Assistant Superintendent" "Port Marine Engineer"
"Client Advisor / Luxury Sales" "Assistant Branch Manager" "Senior Computer Programmer" "Captain D/A Inspector" "Pizza Maker / Coal Oven Cook" "College Print Shop Assistant" "*SR Management Consultant" "Special Assistant IN Mental Retardation" "Human Resources Technician" "Park Borough Commissioner" "*adm DIR Fleet Maintenance NM" "Public Health Adviser" "Education Program Facilitator" "Adjunct Senior College LAB Tech" "Asst TO THE Chairman" "Legislative Clerk" "Stenographic Specialist" "Assistant City Highway Repairer" "Student Aide" "Director OF Plant Operations & Maintenance"
"Chief Asset Management Officer" "Captain Chief OF Counterterrorism" "Mayoral Program Coordinator" "Deputy Controller" "Director OF Investigations" "Program Evaluator" "AIR Pollution Inspector" "Technical Systems Manager" "Director OF Immigrant Affairs" "Election Trainer" "Senior Cook" "AST Commissioner FOR Policy AND Community Resilience" "Special Assistant TO THE Mayor" "Assistant Principal" "Adjunct Professor" "Expediter / Runner" "Director OF Compliance & Legislative Development" "Chief Strategy Officer Ýdoe¨" "Sergeant AT Arms" "Psychiatric Nurse Practitioner (pmhnp)"
"Certified Applications Developer" "Crane Operator Ampes" "Principal Assigned" "Agency Medical Director" "Educational Administrator CSA" "School Social Worker REG SUB" "Forens Mort Tech Coord MRT SRV" "Director OF Management Planning SS" "Locksmith" "Assistant Printing Press Operator" "Helicopter Pilot" "Commissioner OF Community Development" "Executive Deputy Sheriff" "F/T Film Inspection Asst." "Operations Manager" "Criminalist" "Public Administrator" "Disability Coordinator" "Press Secretary Ýdoe¨" "Operations Communications Specialist"
"Planner: Production Cntrl & Scheduling" "Deputy Assistant Chief OF Department" "Telephone Service Technician" "Assistant Director" "Continuing Education Teacher" "Labor Relations Trial Examiner" "Deputy Director OF Housing Applicants" "Director OF Department Advocates Office" "Adjunct Assistant Professor" "Associate Education Analyst" "Director OF Building Management" "Maintenance / Porter" "Assistant TO THE Commissioner" "Superintendent OF Laundries" "Executive Director OF Administration" "Associate Taxi & Limousine Inspector" "Probation Officer Trainee" "Case Mgmt Nurse" "Valet Supervisor" "Captain Detailed AS Chief OF Patrol"
"Catering Coordinator" "Special Advisor TO THE Director" "School Lunch Loader AND Handler" "Admin Asst Campaign FIN Board" "Chief Marine Engineer" "Caseworker" "Senior Consultant" "Customer Information Representative MA L 1549" "Campus Security Assistant" "Associate JOB Opportunity Specialist" "High School Elem Counselor" "Supervising Rackets Investigator Start >4 24 08 NO ABC" "Radio AND Television Operator" "Forensic Mortuary Technician Coord OF Mortuary Services" "Box Office / Membership Sales" "Special Assistant TO THE Chancellor" "Instructor" "Community Assistant" "College LAB Technician" "Chief OF Department"
"Captain Chief OF Community Affairs" "Supervisor Bridge Repairer AND Riveter" "Administrative Consultant" "Statistical Secretary" "JOB Opportunity Specialist" "District Manager OF Administration AND Business Affairs" "Deputy Director OF Emergency Management" "Intelligence Research Specialist" "Quality Assurance Specialist Trainee" "Supervisor Roofer" "Senior Rackets Investigator" "Family PUB Health Nurse" "Visitor Assistant" "Director OF Countermeasures AND Response" "Ice Cream Maker / Pastry Cook" "EOC Assistant TO HEO" "Chief Advisor, Public Space Policy" "Confidential Agency Investigator" "Assistant Director OF Toxicology" "Supervisor OF Traffic Device Maintainers"
"Coordinator OF Criminal Justice" "Manager OF Park License Agreements" "Exec Asst TO THE Commissioner OF Finance" "Nutrition Consultant" "Taxi AND Limousine Inspector" "Valet" "Supervisor OF Motor Transport" "Lmsw" "Interpreter/translator" "Chief Investigating Accountant" "DIR OF Personnel & Labor Rels" "Administrative Deputy Register" "Engineering Work Study Trainee" "Blacksmith" "Director OF Housing Applicantions" "Chemical Engineering Intern" "Captain Detailed AS Chief OF Special Operations" "Director OF Public Information" "EOC IT Assistant" "Junior Public Health Nurse"
"Bridge Painter" "Detective Investigator" "Legislative Administrative Assistant" "Director OF NYC Medical Reserve Corps" "Director OF THE Mayor�s Office OF Operations" "Assistant Deputy Commissioner" "Traffic Device Maintainer" "Special Commissioner OF Investigation NYC School District" "Automotive Specialist" "Director OF Land USE Division" "Senior Estimator" "Statistician" "Youth Development Specialist" "Traffic Enforcement Agent AL 1 & 2 Only" "F/T Group Leader" "Executive Director OF Food Services" "*senior Cook" "Assistant Retirement Benefits Examiner" "Administrative Management Auditor" "Executive Assistant AND Counsel TO THE Public Advocate"
"Administratiive Taxi & Limousine Inspector" "Legislative Analyst" "Deputy City Sheriff NON Spvr" "Metal Work Mechanic" "Administrative Sanitation Enforcement Agent" "Capt DET Chief OF Department" "Computer Operations Manager" "Public Information Officer" "University Assistant Dean" "Sergeantd/a Supervisor Detective Squad" "Teacher Special Education REG SUB" "Supervising Therapist" "Assoc ADM FOR Purchasing Materials MGT & Envir Control" "Confidential Secretary OF Administrative LAW Judge" "Guidance Counselor Assigned A" "Deputy Chief Rackets Investigator" "Legislative Policy Analyst" "Sergeant D/A Supervisor Detective Squad" "Student Aide Vocational" "Director OF Criminal Justice Data Share AND Info Servs QN DA"
"University Payroll Analyst" "*administrative Attorney" "Administrative Storekeeper" "Institutional Aide" "Administrative Director OF Laboratory" "*asist Systms Analyst" "Assistant Housing Manager" "Site / Store Manager" "Supervisor OF School Security" "Membership Consultant" "Psychologist" "Assistant Deputy Administrator" "Deputy Commissioner OF Labor Relations" "RN Staff Nurse (hourly → Annualized)" "Assistant Chief Racket Investigator" "Inspector Construction" "Administrative City Planner" "Cooperative Education Trainee Engineering Aide" "Assistant Laundry Supervisor" "Assistant TO THE Deputy Commissioner"
"Director OF Finance" "Supervisor OF Mechanical Installations & Maintenance" "Associate Education Officer" "Membership Consultant / Sales" "Maintenance" "Bellman/concierge" "Stationary Engineer" "Supervising Housing Groundskeeper" "Educator / Sales Associate" "Secretary TO Member" "Deputy Chief Clerk" "Bartender (concessions)" "Collections Specialist" "Stenographer TO Each Deputy Commissioner" "ADM Manager NON Mgrl From M1/m2" "Service Inspector" "School Medical Inspector Per Session" "Masons Helper" "Deputy Regional Superintendent" "Assistant Chemist"
"Asst PB Hlth ADV" "Legislative Administrative Secretary" "Assoc Water USE Inspector Mgrl" "Personal Stylist" "Assistant TO THE Comptroller" "Dockbuilder" "Peer Counselor" "IT Project Specialist" "City Custodial Assistant" "DIR OF Home Care Services/family AND Adult Services" "Associate Arts Programs Specialist" "Community Liaison Representive" "Executive Deputy Commissioner FOR Mental Hygiene" "*plant Maintainer" "Motor Vehicle Operator" "Student Legal Assistant" "Title Examiner" "Warden Assistant Deputy Warden TED < 11/1/92" "Executive Assistant TO THE Commissioner OF Community Develop" "Deputy Director Legal Division"
"Correctional Standards Review Specialist" "Administrative Horticulturist" "Associate Project Manager" "F/T School Lunch Helper" "Administrative Retirements Benefits Specialist" "Telecommunications Manager" "Concessions Culinary Supervisor" "Scooper / Server" "Teller / Branch Ops" "Director OF Community Planning Boards" "Senior Service Inspector" "Director OF Financing Policy Coordination" "University Engineer Tech" "First Asst Marine Engineer" "Director OF Motor Equipment Maintenance NM" "Delivery Driver (if Used)" "Associate Chief Rackets Investigator" "Psychiatric Nurse (hourly → Annualized)" "Commissioner OF Health" "School Food Service Manager"
"Emergency Medical Specialist Trainee" "Director Employee Assistance Program" "University Administrator" "Asist Systms Analyst" "Recreation Supervisor" "Lecturer" "Counsel TO THE Borough President" "Director OF THE Ombudsman Program" "*senior Estimator" "Public Relations Assistant" "School Medical Inspector" "Chief Administrative LAW Judge" "Prep / Line" "Public Health Nurse" "Senior School Lunch Aide" "Fiscal Responsibility Officer" "Admin Community Relations Specialist" "Director OF Security" "Administrative Public Health Nurse" "Associate Public Records Officer"
"Space Analyst" "Mortgage TAX Examiner" "Secretary TO District Attorney" "Employee Assistance Program Specialist" "Member OF THE Housing Authority" "Front Desk Associate" "Special Assistant TO THE Human Resources Administrator" "Captain Detailed AS Assistant Chief Inspector" "Cement Mason" "Secretary OF Comm" "IT Assistant" "Associate Staff Analyst" "Senior Sewage Treatment Worker" "Substitute Recreation Assistant" "Nurse Practitioner" "Public Health Educator" "Security Officer" "Director OF THE Office OF Immigrant Affairs" "Inspector Boilers" "Executive Legislative Coordinator"
"Publishing Associate" "Administrative Engineer" "Secretary TO THE Deputy Chancellor" "Office Machine Aide" "Shift Manager" "Confidential Asst TO THE Executive Deputy Commissioner" "Delivery Driver (some Shops)" "Chief OF Intelligence & Counterterrorism" "Legislative Information Officer" "Administrative Assistant TO THE Mayor" "Director OF Intergovernmental Affairs" "Captain D/A Deputy Chief Inspector" "Spa Therapist" "School Crossing Guard" "Assistant Teacher" "Confidential Asst Office OF District Attorney, King County" "Special Assistant" "Director OF Community Relations" "Executive Assistant TO THE Human Resources Admin" "Deputy Commissioner OF Investigations"
"Precinct Receptionist" "Buyer / Purchasing Specialist" "Chief Investigator" "Associate Traffic Enforcement Agent" "Caretaker" "Parking Attendant" "Grocery Associate" "Server / Waitstaff" "Hccs SR College LAB Tech" "Principal Title Examiner" "Environmental Police Officer Managerial" "Sanitation Enforcement Agent" "Admin Schl Secur MGR MGL" "Chief Office Assistant" "DIR OF Contract Mgmt & Intergovernmental Relations" "Supervisor OF Traffic Device Maintainers Level 1 Only" "DIR OF Administration, Worker's Comp Benefits" "Assistant Architect" "Director OF Information Systems" "Executive Administrator OF Gracie Mansion"
"Curatorial Assistant" "University Associate Administrator" "Executive Director OF Public AND Private Partnerships" "Director OF Community Assistance Unit" "Elevator Mechanic" "Risk Management Officer" "Market Agent" "Project Planner" "Vending Prep" "Instructor (cycling/class)" "Associate Benefits Opportunity Specialist" "Chief Engineer" "Director OF Elder Abuse Program Services QN DA" "Supervisor Electrician" "Program Producer" "Client Advisor / Sales" "Deputy Assistant Commissioner FOR Evaluation" "Director OF Fiscal Operations" "Administrative Construction Project Manager" "College Print Shop Specialist"
"Director OF THE Office OF Scheduling & Executive Operations" "Kitchen / Line Cook" "Cuny ART Model" "Supervisor Bricklayer" "College Print Shop Associate" "School Social Worker" "Chief Operating Officer" "Captain Detailed AS Chief OF Operations" "*systems Analyst" "NON Teaching Adjunct II" "Executive Director OF Materials FOR THE Arts" "Exec Asst TO THE Deputy Commissioner" "Medical Receptionist / Front Desk" "Counsel" "Protection Agent" "Assistant Housekeeper" "Chief City Medical Examiner" "Deputy Director OF Administration" "Bookbinder" "Deputy Commissioner FOR Administation"
"Key Holder" "Server (tipped)" "Concessions / Bar" "Public Health Sanitarian" "Assistant TO THE Chairman" "Associate Director OF Nursing Services" "Director OF Administration" "Warehouse Supervisor" "Deputy Director OF Headstart Program" "Second Deputy Comptroller" "Emergency Service Aide" "Clerical Associate" "Donation Attendant" "College Accounting Assistant" "Special Advisor TO THE Mayor FOR Health Services" "Director OF Headstart Program" "Director Employee Management Division" "Secretary TO ONE Deputy Commissioner" "Special Assistant Cannabis NYC" "Executive Assistant TO THE Director OF Administration"
"Higher Education Officer/asst Administrator" "Senior Policy Advisor" "Senior Legislative Policy Analyst" "Construction Project Manager" "Deputy Administration Assistant" "Teacher Assigned A" "Agency Security Director" "Assistant Commissioner FOR Facilities Operations" "Executive DIR OF Administration" "*supervisor" "District Supervisor" "NEW York City Urban Planning AND Design Fellow" "Jewelry / Watches Specialist" "Executive Director OF THE Commission ON Gender Equity" "Special Assistant TO DA" "Personnel Director Health Care Facilities" "Captain Chief OF Intelligence" "Counter / Cashier" "Deputy Asst Admin FOR Personnel ADM & Labor REL" "Customer Service / Office"
"Group Fitness Instructor" "Chief Administrator OF Impartial Hearings" "Pizza Maker" "Area Manager" "Admin Traffic ENF Agnt" "Watchperson" "Executive Assistant FOR Planning" "Battalion Chief" "Business Data AND Reporting Analyst" "Program Specialist Correction" "Special Commissioner OF Investigation NYC School Dist. DOI" "Spec Consultant" "Senior Systems Analysts" "Front Desk / Guest Services" "Legal Secretary" "Commissioner OF Emergency Management" "Water USE Inspector" "Client Advisor" "Annual ED Para" "EOC IT Support Assistant"
"Assistant Plan Examiner" "Director OF Internal Auditing" "Wealth / Financial Advisor" "Deputy Counsel" "Assistant Corporation Counsel" "*associate Executive Director" "Council Member" "Sales Associate / Cashier" "Admin DIR OF Laboratory" "Senior Medical Specialist" "Executive Deputy Commissioner" "Secretary TO THE Chair, Landmarks Preservation Commission" "Senior Administrator" "Department Supervisor" "Store Lead" "Superintendent" "Fire Alarm Dispatcher" "Admin Schl Secur MGR" "Assistant Dean" "Legislative Attorney"
"Secretary TO THE Corporation Counsel" "Community Planning Board Coordinator" "Associate Administrator" "Admissions Associate" "Customer Information Representative" "Administrator" "Director OF THE Office OF Collective Bargaining" "Administrative Education Officer" "Supervisor OF Radio AND Television Operators" "Counsel TO THE Public Advocate" "Commissioner OF Design & Construction" "Associate Water USE Inpector" "ADM School Security Manager U" "Trainer / Instructor" "Line Cook / Prep" "Secretary TO Commissioner OF Bldgs" "Asst Director OF Intergovermental REL FOR City Legist Affs" "ADM Manager NON Mgrl" "Investment Trustee Deferred Compensation" "Secretary TO THE Commissioner OF Bldgs"
"Deputy Director OF Construction" "Director OF Communications" "Principal Investigator" "Property Clerk" "Senior Systems Analyst" "Analyst (ib/wealth)" "Administrative Procurement Analyst NON Mgrl" "*assist Coordinating Manager" "Asst Commissioner FOR Planning & PRG Deve" "Deputy Director OF Design" "Guidance Counselor REG SUB" "Executive Assistant TO THE Chief Administrative LAW Judge" "Coordinator, Election DAY Operations" "Personal Stylist / Sales Professional" "Area Manager OF School Maintenance" "City Mortuary Technician" "*principal Park Supervisor" "Captain Detailed AS Chief OF Interagency Operations" "Inspector Elevators" "Loss Prevention"
"Repair Crew Worker" "Special Assistant To The Director" "Associate Dean" "NEW York City Urban Fellow" "Supervisor I Social Work" "Associate Public Health Sanitarian" "Director OF Invest Accounting AND Econ Crimes Investigation" "Secretary TO THE Commissioner OF Labor Relations" "Director OF Direct Service Programs" "Chief OF Staff TO THE Mayor" "Clock Repairer" "Certified Wide Area Network Administrator" "Administrative Program Officer" "Commissioner OF Citywide Administrative Services" "Asst Commissioner FOR Agency Preparedness AND Response" "Psychologist IN Training" "OIL Burner Specialist" "Coop Education Trainee Computer Tech Aide/jr" "Admin Traffic ENF Agnt Union" "Election Worker"
"Legal Secretarial Assistant" "Baker / Dough Prep" "Commissioner OF Finance" "Crew / Server" "Tests AND Measurement Specialist" "Assistant TO THE Mayor" "Housekeeping Manager" "Principal Custodial Supervisor" "Senior Physical Therapist" "Commissioner OF Parks & Recreation" "Cafe Leader" "Inspector Hoists AND Rigging" "Assistant TO City Administrator" "Supervisor Assigned" "SR Healthcare Prog Plan Anlyst" "Research Analyst TO THE Public Advocate" "F/T DC 37 Family Para" "DIR OF Materials Management" "Front Desk / Membership Sales" "Deputy Director Office OF Communications"
"Attending Physician" "Sergeantd/a Special Assignment" "Deputy Director OF Probation" "ASS Commissioner Design AND Construction Management" "Kitchen Manager" "Confidential Secretary TO THE Deputy Commissioner" "Director OF Health Care Program Planning/analysis" "Concessions Cook" "Teacher Assistant REG SUB" "Executive Program Specialist" "Client Service / Branch" "Senior Automotive Service Worker" "Assistant Superintendent" "Administrative Project Manager" "Sergeant D/A Special Assignment" "Insider" "ADM Traffic Enfrcmnt Agent" "Coordinator, Tenant Patrol" "Legislative Messenger" "Truck Operator/server"
"EOC Lecturer/ Doctral Schedule" "Executive Asst TO THE Commissioner" "Director OF Management & Planning" "Secretary TO THE Deputy Boro President" "Commissioner OF Business Services" "Associate Fingerprint Technician" "Captain Detailed AS Chief OF Training" "Secretary TO THE President" "Research Assistant" "Commissioner OF Cultural Affairs" "Project Director" "Associate Commissioner FOR Personnel Service" "Principal Accountant Investigator" "Director OF Public & Community Relations" "Assistant Landscape Architect" "Administration Public Record Officer" "Real Property Assistant" "Supervisor OF Electrical Installations & Maintenance" "Education Analyst" "Valet (w/tips)"
"Chief Information Officer" "Assistant Director OF Forensic Biology" "Chief Strategy Officer" "Concourse Supervisor" "Agency Attorney Interne" "Mail/message Services Worker" "Supv OF Housing Exterminators" "Commissioner OF THE OFC TO END Domstc AND Gend Based Violce" "Tractor Operator" "Incinerator Facility Manager" "*cook" "Reporter/ Stenographer" "Franchise Manager" "Associate Commissioner FOR Employment Service" "Product Trainer" "Private Secretary" "Legislative Representative" "Desk Associate" "School Secretary PER Session" "ADM School Security Manager"
"Communications Officer" "Administrative Director OF Marine Maintenance" "Captain Detailed AS Chief OF Detectives" "Aspiring Principal" "Third Deputy Comptroller" "NON Teaching Adjunct III" "City Attendant" "Analyst (ib/sales)" "Commissioner OF Dept OF Info Technology & Telecommunications" "Energy Conservation Specialist" "School Plant Manager" "Assistant Caretaker" "Forester" "Deputy Director OF Equal Opportunity" "City Parking Equipment Service Worker" "Mate" "Psychiatrist I" "Senior Adminisrator" "Supervisor OF Stock Workers" "Loan Officer / Mortgage Specialist"
"Administrative Actuary" "Delivery Driver (where Offered)" "First Deputy Commissioner" "Special Deputy Comptroller" "Juvenile Counselor" "Administrative Parks & Recreation Manager" "Helicopter Mechanic" "Director OF Correctional Standards Review" "Administrative Superintendent OF Bridge Operations" "Houseparent Aide" "*surgeon" "Agency Attorney Intern" "Director OF Criminal Justice" "Member, Civilian Complaint Review Board" "Gelato Maker" "Police Administrative Aide" "Director OF Organized Crime Control PD" "Facility Manager" "Substitute ED Para" "Maintenance Technician"
"Chief Dockmaster" "Chief Consultant" "Teacher REG SUB" "Administrative Housing Manager" "Teaching Artist" "Associate Quality Assurance Specialist" "Director OF Noise Abatement" "Chief Rackets Investigator" "Supervisor Sheet Metal Worker" "Assistant Commissioner, Citywide Pymt Svcs & Stnds" "EOC Higher Education Assistant" "Spvsg FAD Asst Commiss Detail" "Sanitation Compliance Agent" "Senior Police Administrative Aide" "Chief Review Assessor" "Pipe Caulker" "Playground Associate" "Floor / Shift Lead" "Commissioner Designated AS Vice Chairman" "Asbestos Handler Supervisor"
"Senior Staff Officer" "Deputy Commissioner FOR LAW Enforcement" "DEP DIR OF Audit & Prog Analysis" "Lead Abatement Worker" "F/T School Aide" "College Accountant" "Store Manager / General Manager" "Computer Systems Manager" "Labor Relations Analyst" "Cashier (truck)" "Gasoline Roller Engineer L15" "University Dean" "Director OF Management Information Services" "Police Communications Technician" "Administrative Accountant" "Supv OF Housing Exterminator" "School Psychologist REG SUB" "Administrative TAX Auditor" "Director OF THE Mayors Office OF Administrative Services" "*personnel Program Developement Specialist"
"Manager / Supervisor" "Catering Manager / Events" "Pilot" "Surgeon Detailed AS Deputy Chief Surgeon" "Asst Commissioner FOR NON Secure Detention Juvenile Justice" "Senior School Neighborhood Worker" "Merchandise Supervisor" "DEP Commissioner FOR Community Relations" "Captain: Chief OF Transportation Bureau" "Director OF Training" "Adjunct Lecturer" "Higher Education Assistant" "Supervising Public Health Adviser" "*housing Caretaker" "NEW Leader" "Sewage Treatment Worker" "Supervising Demolition Inspector" "Coop Education Trainee Computer Tech Aide/sr" "School Business Manager" "Salon Manager"
"Director OF Parent Involvement" "Supervising Communication Electrician" "Legislative Coordinator" "Chief, Publications & Reports" "Deputy Executive Director OF Financial Operations" "Housekeeping Attendant" "Deli Clerk" "Film Manager" "Administrative Energy Conservation Specialist" "Assistant TO HEO" "Chief OF Staff TO First Deputy Commissioner" "Education Assistant" "Executive Cook" "Spa Attendant" "Administrative Supervisor OF Building Maintenance" "Assistant TO Commissioner" "Executive Asst Domestic Violence HRA" "Analyst" "Assistant Chemical Engineer" "Medical Specialist"
"Special Assistant TO THE First Deputy Commissioner" "X RAY Technician" "Senior Advisor FOR Investigations" "Administrative Staff Analyst" "Oiler" "Coordinator, Voter Registration Activities" "Executive Assistant TO THE Commissioner" "Criminalist Director OF Laboratory" "Cashier / Pay Station Operator" "Guest Service Agent" "Deputy Director OF Community Planning Boards" "Kitchen Team / Pizza Maker" "Picker/packer" "School Psychiatrist" "Director OF Food Stamp Program" "Director Office OF Policy" "Manager, Water Supply" "*certified Wide Area Network Administrator" "Guest Experience Associate" "Personal Banker / Customer Service Rep"
"SR Systems Analyst EDP" "Store Leader" "Assistant Comissioner FOR Family Operations" "Chief Fire Marshal" "Director OF General Services" "Head Nurse" "EOC College LAB Technician" "Associate Inspector" "Staff Analyst Trainee" "Director OF Community Planning Boards MGL Assign" "Deputy Director OF Health AND Safety" "Teacher PER Session" "Director OF Information Services" "Assistant Counsel PD" "Director OF Motor Transport" "Hearing Examiner" "Secretary TO THE Chairman" "Pizza Cook / Oven" "Supervisor Locksmith" "Director OF Race Equity Strategies"
"Assistant Environmental Engineer" "Scientist" "*certified Applications Developer" "Higher Education Associate" "Front Of House / Usher" "Director OF Advocacy" "Director OF Crisis Assistance AND Training" "Senior Salvage Appraiser" "Commissioner, UN & Consular Corps Diplomatic Relations" "University Architect" "Senior Housekeeper" "Counsel TO THE Chancellor" "Director Borough President's Office OF Administration Queens" "City Laborer" "Legal Secretarial Assistant AL 1 Only" "Ice Cream Maker / Batch Maker" "Food Service Helper" "Teacher General ED" "Assistant City Assessor" "Chief Caretaker"
"Auto Body Worker" "DEP DIR MTR EQ Mntc" "Electrical Engineering Intern" "Administrative Juvenile Counselor" "Executive Director OF Fleet Operations" "Minority Leader" "Administrative Attorney" "* Attending Dentist" "Director OF News Bureau" "Contract Reviewer" "Deputy Commisioner" "F/T SR. School Lunch Helper" "Consultant ON Race Relations" "Senior Adviser TO THE Commissioner" "Director OF Property Management" "Scooper" "Policy Advisor TO THE Chancellor Ýdoe¨" "Senior Deputy Commissioner" "Plasterer" "Executive Director OF Gracie Mansion"
"Special Assistant TO THE Deputy Executive Director" "IT Service Management Specialist" "Senior Custodial Supervisor" "Beauty Advisor (premium Brands)" "Deputy Chief City Medical Examiner" "Administrative Assistant TO Community Education Council" "Senior Stationary Engineer" "First Deputy Commissioner General Counsel" "Attendant" "Assistant Superintendent OF Welfare Shelters" "Substitute School Guard" "Director OF Review & Counseling" "*dir OF Fiscal Affairs" "EOC Higher Education Officer" "Counsel TO THE Mayor" "Valet Attendant (base Wage)" "Assistant Mechanical Engineer" "Assoc Inspector" "Housing Exterminator AL IV" "Director OF Development"
"Police Attendant" "Housing Caretaker" "Teacher Assigned B" "Water Treatment Plant Operator L1" "University Assistant Administrator" "Medical Investigator" "Legislative Support Service Coord" "Director OF Photographic Services PD" "Thermostat Repairer" "Fire Marshal" "Projectionist / AV Tech" "Director, Office OF Operations" "Cooperative Education Trainee Legislative Clerical Assistant" "Psychiatric Nurse Practitioner (per Diem; Hourly → Annualized)" "Park Supervisor" "Housing Assistant Trainee" "Admin Inspector" "Correctional Counselor" "School Lunch Aide" "Cooperative Education Trainee Seasonal Park Help"
"Deputy Mayor" "Monitor" "Adult Educat Teach REG SUB" "Assistant Chief OF Department" "Director OF Management Design" "Confidential Assistant TO Boro President" "Medical Officer" "Chief Lifeguard" "CSE Chairperson" "Deputy Borough Commissioner" "Director OF Artworks" "Administrative Education Analyst" "Environmental Engineering Intern" "Associate Commissioner" "Senior Institutional Trades Instructor" "Director OF Field Operations" "Secretary TO Deputy Commissioner" "Senior Project Planner" "Director OF Stores" "Secretary OF THE Department"
"Commissioner OF Housing Preservation & Development" "Emergency Preparedness Manager" "Secretary TO THE Department" "Floor Lead / Supervisor" "Visitor Services" "Borough Manager, Office OF Neighborhood Safety" "Special Assistant TO THE Borough President" "Administrative Quality Assurance Specialist" "Senior Rackets Investigator Start >4 24 08 NO ABC" "City TAX Auditor" "Lot / Truck Attendant" "Telecommunications Specialist" "*first Asst Marine Engineer" "Administrative Procurement Analyst" "Assistant Advocate PD" "Bellman/doorman" "DEP DIR Research & POL Develp" "Manager, Water AND Sewer Systems" "Director OF Support Services PD" "Deputy Chancellor Financial Affairs"
"Branch Manager" "Computer Programmer Analyst" "Systems Analyst" "Associate Chemist" "Clerical Associate Most Mayoral AG" "Cuny Administrator Assistant" "Administrative Psychologist" "Districting Commission Administrative Assistant" "Director" "Prepared Foods Cook" "Deputy Comptroller" "Computer System Manager" "Cooperative Educational Trainee" "SR Project Planner" "College Graph Designer" "Commissioner OF Transportation" "Nycaps Process Analyst" "Probation Officer" "Supervisor II" "Special Advisor TO City Clerk"
"Research Projects Coordinator" "Supervisor Painter" "Ice Cream Maker" "Assistant TO THE Commissioner OF Parks AND Recreation" "Research & Liaison Coordinator" "Director OF THE Office OF Correspondence" "Assistant Captain" "Assistant Director OF Finance" "Press AND Speech Aide" "Substitute Principal" "Administrative Inspector" "Sergeant" "Donation Attendant / Receiver" "Director Office OF Communications" "Secretary TO THE Commissioner OF DDC" "Assistant Commissioner Of Information Technology" "Lead Theatre Technician" "Assistant Director OF Neighborhood Safety" "Housing Development Specialist" "Executive Director OF Professional Development"
"Enforcement Officer / Revenue Control" "City Planning Technician" "Ticket Taker" "Administrative Landscape Architect" "Supervisor OF Radio Repair Operations" "Project Manager" "Multiple Dwelling Specialist" "EOC Office Assistant" "Counselor" "Ship Carpenter" "Counter Cashier" "Engineering Technician" "Highway Repairer" "Director OF Audit AND Program Analysis" "Carriage Upholsterer" "Administrative Probation Officer" "Director OF Forensic Biology" "Assistant Chief Fire Marshal" "Executive Director AND Chair, Commission ON Racial Equity" "Puppeteer"
"Comptroller" "Administrative Retirement Benefits Specialist" "Agency Chief Contracting Officer" "Baker" "Graphic Artist" "Principal Police Communication Technician" "City Service Aide" "Director OF Regional Joint Interest Park" "Bridge Repairer AND Riveter" "Senior Detective Investigator Start >4 24 08 NO ABC" "Senior Administrative Assistant" "Executive Deputy Administrator" "Captain D/A Deputy Chief" "Assistant Director OF Education" "General Inspector" "Assistant Director OF Administration" "Assistant Commissioner FOR Management ACD Doss" "Lieutenant" "E Commerce / Online Sales Associate" "Asst DIR OF Intergvnmental Reltns FOR THE Albany Office"
"Clerk TO THE Board" "Supervising Chief Surgeon" "Administrative Graphic Artist" "City Park Worker" "Chief Financial Officer" "Environmental Police Officer" "Public Records Aide" "Resident Physician" "Criminalist Deputy Director OF Labatory" "Delivery Driver (franchises Vary)" "Supervising Fire Marshal" "Hearing Officer" "Retail Staff" "Nutritionist" "Mechanical Engineering Intern" "Tailor/alterations" "Counter / Retail Associate" "Assistant DIR OF Administration" "Deputy Director OF Communications" "Prinicipal Human Rights Specialist"
"Department Manager" "Nurse Practicioner" "City Security Aide" "Director OF Scheduling" "Counter/takeaway" "Key Holder / Shift Lead" "School Medical Inspector REG SUB" "Associate Director, Borough Improvement Board" "Supervising Police Communications Technician" "Educational Administrator UFT" "Assistant TO THE Public Advocate" "Director OF Budget Studies & Economic Research" "First Assistant Corporation Counsel" "Agency Deputy Medical Director" "Recreation Specialist" "Executive Director OF Healthcare Systems Readiness" "Front Desk / Desk Associate" "Capt DET Chief OF THE Housing Bureau" "Concessions Cashier / Customer Service Associate" "Sales / Client Associate"
"Commissioner OF Homeless Services" "Dessert Cook" "Buyer / Vintage Specialist" "Associate Executive Director" "Deli Worker" "Interpreter" "Director OF Public Health Emergency Planning" "Secretary TO THE Comptroller" "Events / Catering Assistant" "Secretary TO THE Chief Actuary" "Borough Director OF Recreation" "Equal Rights Compl Spec" "Principal Park Supervisor" "Supervisor OF Elevator Maintenance" "Warden Deputy Warden IN Comm TED < 11/1/92" "Deputy Chancellor" "College Print Shop Coordinator" "Supervisor I" "Councilmanic Aide" "Senior Baker"
"School Lunch Assistant Cook" "Chief School Business Executive" "Public Health Assistant" "Associate Professor" "Director Urban Archaeology LPC" "*director OF Health Care Program Planning/analysis" "Communications Director" "Supervising Bookbinder" "Child Protective Specialist Supervisor" "Consumer Advocate" "Associate Director Operational Services" "Director Criminal Justice Data Share AND Info Services" "Contract Specialist" "Director OF Cyber Crime Forensics" "Customer Service Rep" "Director OF ALT Sentencing AND Offender RE Entry Progs QN DA" "NEW York City Fellow" "Staff Assistant" "Procurement Analyst" "Administrative Borough Superintendent"
"Chief Actuary" "Sandwich Artist" "DEP DIR OF Social & Comm Serv" "Computer Operator Manager" "Director OF THE Mayors Office OF Appointments" "Department Librarian" "Project Manager Intern#" "Special Assistant TO THE Executive Director" "Buyer / Curator" "Director OF Probation" "Executive Secretary" "Commissary Manager" "Senior Automotive Specialist" "Research Scientist" "Director OF Management & Budget" "School Psycholgist" "Research AND Liaison Coordinator" "Field Supervisor" "Director OF Research & Policy Development" "Staff Audiologist"
"Interpreter/translator DOE" "Administrative School Food Service Manager" "Director OF Motor Equipment Maintenance" "Climber & Pruner" "Substitute SR. School Lunch Helper" "Director OF Intergovernmental Relations" "Chair" "Capt DET Chief OF Internal Affairs" "Executive Assistant Midtown Enforcement" "Special Consultant" "Cook / Kitchen" "Captain Detailed AS Chief OF Personnel" "Child Welfare Specialist Supervisor" "Sorter / Donation Processor" "Executive Director, Citywide Event Coordination & Management" "Senior Title Examiner" "Intelligence Research Manager" "Special Assistant TO Member OF THE Board OF Education" "Marine Electronics Technician" "Associate School Food Service Manager"
"Director OF Public Relations" "Supervising Accountant Investigator" "Supervising Probation Officer" "ADM Traffic Enfrcmnt Agent Director OF Parking Enfrcmnt Dist" "Senior Policy Advisor TO THE Mayor" "Director Bureau OF Weights AND Measures" "Special Assistant TO THE President" "Makeup Artist / Services" "Medicolegal Investigator" "Director OF Consumer Information" "LAB Specialist/assistant REG SUB" "Environmental Engineer" "Hostler" "Captain Detailed AS Chief OF Risk Management" "Computer Operator" "Steam Fitter" "Asst Commissioner FOR Policy AND Community Resilience" "Stylist" "Assistant Counsel" "School Computer Technology Specialist"
"Consultant Public Health Nurse" "*dentist" "Computer Aide" "Director OF Nursing Services" "Children's Counselor" "Worker's Compensation Benefits Examiner" "Council Member Aide" "Intelligence Research Manager PD" "Administrative Landmarks Preservationist" "Senior Press Officer" "Counter/cashier" "Assistant TO Police Commissionor" "Deputy Executive Director Campaign Finance Board" "Director, Office OF Administration" "Supervisor Plumber" "Deputy Counsel Intern" "Lot Manager / Site Manager" "Associate Parking Control Specialist" "City Register" "Associate Investigator"
"Donation Specialist / Pickup Driver" "Assistant TO THE Deputy Mayor" "Education & Vocat Counselor" "Supervisor / Manager" "Deputy Operation Support Manager" "Director OF Construction" "Secretary TO Public Administrator" "High School Student Aide" "Secretary OF THE Authority" "ADM Manager" "Educator" "Deputy Director OF Medicolegal Investigations" "Cuny Secretarial Assistant" "Director OF Equipment" "Executive Director, Special Projects & Community Events" "Administrative Fire Protection Inspector" "College Interior Designer" "TAX MAP Cartographer" "Asst Comm Prgm DEV Revw HMH" "Senior Student Legal Specialist"
"Administrative LAW Judge" "Civil Engineer" "Chief Pension Investment Advisor, Finance" "Director OF Energy Conservation" "Vice President" "*assistant Advocate PD" "Chief OF City Sheriff Operations" "Secretary TO THE First Deputy Commissioner PD" "Pizza Baker / Oven" "*SR Systems Analyst EDP" "Administrative Community Relations Specialist" "Executive Director ON Commission ON Gender Equality" "Retail Sales" "Maintenance / Grounds" "Housing Development Specialist Trainee" "Director OF Policy Analysis" "Valet Attendant (base)" "Legislative Fiscal Officer" "Facilities Coordinator" "*senior Staff Officer"
"Senior Intergroup Relations Officer" "Assistant Transportation Specialist" "Counter / Slice Staff" "Front Desk / Sales Associate" "Director FOR Equal Employement Opportunity" "Stocker" "Coach" "Front Desk / Membership" "Shift Lead" "Counter Staff" "Traffic Enforcement Agent" "Public Health Emergency Preparedness Specialist" "Principal Fingerprint Technician" "P/T DC 37 Family Para" "Night Attendant" "Deputy Inspector General" "Precinct Community Relations Aide" "F/T School Guard" "College Assistant" "Senior Legislative Financial Analyst"
"Director OF Crime Strategies AND Analysis" "Assistant Highway Transportation Specialist" "Community Associate" "Director Management Information Systems" "Director OF School Safety" "Jewelry Specialist / Watch Specialist" "Special Officer" "Assistant Civil Engineer" "Plumber's Helper" "Landscape Architect Intern" "Deputy Chief OF Staff" "President" "Director OF Eeo/contract Compliance" "Housing Assistant" "Real Property Manager" "Chairman" "*senior Systems Analyst" "Executive Asst TO THE NYC Commission TO THE United Nations" "Food Service" "Assistant Executive Secretary"
"Assist Commissioner FOR Policy Analysis & Prog Deve" "Higher Education Officer" "Supervisor Elevator Mechanic" "Admin School Security" "Administrative Labor Relations Analyst" "Parking Control Specialist" "Director OF Methods & Analysis" "Computer Specialist" "Associate Sanitation Enforcement Agent" "Deputy Chief Strategy Officer Ýdoe¨" "Equal Rights Compliance Specialist" "Concessions Warehouse Associate" "Deputy Assistant Director" "Counsel TO THE Police Commissioner" "Guest Services Agent / Representative" "Supervising Housekeeper" "Warden" "Site Manager" "Asst DIR OF Intergvnmentl Relatns FOR THE Washngtn OFF" "Steam Fitter's Helper"
"Associate Housing Development Specialist" "Geologist" "Director Of Public And Community Relations" "Advisor FOR Gay, Lesbian, Transgender Issues" "Physician" "Police Cadet" "Supervisor Thermostat Repair" "IT Support Assistant" "Director OF Television" "Director OF Social Services" "Director OF Clinical Laboratories" "Civilianization Manager PD" "Teacher Attendance REG SUB" "Electrician's Helper" "P.o. DA DET GR3" "Administrative Superintendent OF Highway Operations" "Emergency Prepardness Manager" "Director OF Leased Housing" "Sorter / Pricer" "Chief Administrator Supt Campus B/G"
"Scooper / Counter Staff" "Secretary TO Department" "Hearing Director" "Administrative Transportation Coordinator" "Lot Supervisor" "Deputy General Counsel" "Asst Commissioner FOR Public & Legis Affairs" "Legislative Programmer/analyst" "Superintendent OF Water AND Sewer Systems" "Assistant Urban Designer" "Senior Photographer" "Director OF Urban Park Ranger Program" "Controller" "Administrative Real Property Manager" "Borough President" "*procurment Analyst Level Iii, OJ" "Rigger" "Director OF Medical Assistance Program" "Manager / FOH Lead" "Administrative Director OF Social Services"
"Secretary TO THE Executive Director OF Retirement System" "Supervising Fire Alarm Dispatcher" "Food Prep (concessions)" "Motor Grader Operator" "Asst Commissioner" "Administrative Public Records Officer" "Director OF Community Involvement" "NON Teaching Adjunct I" "Director OR Management" "Director, Energy Management Strategy" "Psychiatric Nurse (estimate)" "Admin Traffic Enfrcmnt Agent" "Secretary TO Conflicts OF Interest Board" "Management Auditor" "Community Supertindent" "Assoc Commissioner FOR Planning,review AND Evaluation" "Mental Health Therapy Aide (mhta)" "Delivery Driver / Runner" "Supervising Human Rights Specialist" "Legislative Investigator"
"Chief Service Officer OF NYC Service" "Visual Merchandiser" "Registered Nurse (hourly → Annualized)" "Confidential Strategy Planner" "IT Associate" "Commissioner OF Department OF Veterans Services" "Per Session ED Para" "*supvsng Systems Analyst" "Cuny Office Assistant" "Director OF Biodetection AND Response" "Staff Analyst" "Jewelry Specialist / Gemologist" "College Aide" "Collections Unit Head" "Capt DET Chief OF THE Transit Bureau" "Disability Accommodations Specialist" "Life Guard" "Inspector" "University Assistant Engineer" "Captain Detailed AS Assistant Chief"
"Director OF Equal Opportunity" "Associate Juvenile Counselor" "Secretary TO THE Deputy Commissioner" "Director OF Community Engagement AND Response" "Plan Examiner" "*adm DIR Fleet Maint Mgrl Asgmnt" "Construction Laborer" "General Manager" "Clerical Aide" "Licensed Clinical Social Worker (lcsw)" "Director OF Plan & Field Services" "Crime Analyst" "Executive Assistant TO THE First Deputy City Clerk" "Deputy Director OF Labor Relations" "*custodial Assistant" "Custodian" "Warden Deputy Warden TED < 11/1/92" "Housing Exterminator" "Front Desk" "Associate Engineering Technician"
"Supervisor OF Investigators" "Private Banking / Wealth Associate" "Public Health Education Trainee" "Usher / Ticket Seller" "Apprentice Inspector" "Assistant Professor" "Supervisor OF Housing Stock Workers" "Paralegal Aide" "Eligibility Specialist" "Admin Contract Specialist" "Supervisor OF Child Care" "Summer Graduate Intern" "Strategic Initiative Specialist" "Secretary TO THE Commissioner OF Correction" "Senior Detective Investigator" "JR Phnurse" "Inspector General" "Events / Catering Staff" "House Manager / Supervisor" "Investigative Manager"
"Supervisor Steamfitter" "Director OF Operations" "Deputy Commissioner Film Office" "Supervisor Boiler Maker" "Certified IT Developer" "Ferry Terminal Supervisor" "Director OF THE Mayors Office OF Operations" "Roofer" "Commissioner OF Environmental Protection" "Executive Assistant TO THE First Deputy Clerk" "Director OF Audits" "Deputy Director OF Methods & Analysis" "Assistant Commissioner FOR Facilities Development & Const" "Deputy Commissioner OF IT" "Secretary TO Assistant TO President" "Associate Fraud Investigator" "Customer Service Associate" "DEP Director OF Personnel & LR" "Department Clerk" "Associate Urban Park Ranger"
"Corporation Counsel" "Management Auditor Trainee" "Substitute School Lunch Helper" "Director OF Crim Justice Data Share AND Info Servs KDA" "Seasonal Associate" "Concessions" "Director Borough Improvement Board" "Deputy Director OF Motor Equipment Maintenance" "Administrative Assessor" "Boiler Maker" "Voting Machine Technician" "Speaker/majority Leader" "Supervisor Bridge Painter" "Executive Assistant TO THE Comptroller" "Deputy Borough President" "Assistant Accountant" "Associate Commissioner FOR Management" "Retail/thrift Associate" "Borough Commissioner" "Computer Aide NON Spvr"
"Blacksmith's Helper" "Community Service Aide" "Medical Record Librarian" "Trainer Assistant" "Director OF Mental Health Disaster Preparedness" "Assistant Commissioner OF Labor Relations" "Senior Game Advisor" "Spvsg FAD DEP DIR Dsptch Dtail" "Assistant Secretary TO THE Comptroller" "Dough / Prep" "Asbestos Hazard Investigator" "Examining Attorney" "Captain Detailed AS Chief OF Strategic Initiatives" "Associate Call Center Representative NON Spvr" "Client Advisor / Boutique Sales" "Usher / Floor Staff" "Compositor" "F/T Health Service Aide" "Geek Squad Agent" "Teacher Trainer"
"Deputy Director Finance" "Intelligence Research Specialist PD" "Administrative Housing Development Specialist" "Deputy Commissioner FOR Policy AND Analysis" "Admin Housing Development Spec" "Poison Information Specialist" "Legislative Counsel" "Projectionist / AV / Programmer Tech" "Examiner OF Accounts" "Beauty Advisor / Sales" "Registered Nurse" "Warden Deputy Warden IN Comm" "Psychologist IN Train REG SUB" "Front Desk / Operations" "Admin Landmarks Preservationist" "Director OF Investments" "Special Assistant TO THE DA" "Deputy Commissioner, Strategic Initiatives" "Adult ED 35 H" "Supervising Emergency Medical Service Specialist Dpty Chiefs"
"First Deputy Comptroller" "Financial Advisor / Wealth Associate" "Letterer AND Sign Painter" "Associate Public Information Specialist" "Bookseller" "Front Desk / Customer Service" "Asphalt Plant Manager" "Auto Machinist" "*research Scientist" "Secretary TO THE Deputy Chair" "Director Correspondence Services" "Fire Safety Cadet" "Chauffer Attendant" "Floor Staff (usher/concessions/box Office)" "Procurment Analyst Level III" "Ombudsman" "Chairman Commission ON Human Rights" "Legislative Administrative Manager" "Wiper"];

const JobSearchDropdown: React.FC<JobSearchDropdownProps> = ({
  value,
  onChange,
  onBlur,
  placeholder = "Search or select a job role...",
  className = ""
}) => {
  const [isOpen, setIsOpen] = useState(false);
  const [searchTerm, setSearchTerm] = useState('');
  const [filteredOptions, setFilteredOptions] = useState(JOB_OPTIONS);
  const dropdownRef = useRef<HTMLDivElement>(null);
  const inputRef = useRef<HTMLInputElement>(null);

  useEffect(() => {
    const filtered = JOB_OPTIONS.filter(job =>
      job.toLowerCase().includes(searchTerm.toLowerCase())
    );
    setFilteredOptions(filtered);
  }, [searchTerm]);

  useEffect(() => {
    const handleClickOutside = (event: MouseEvent) => {
      if (dropdownRef.current && !dropdownRef.current.contains(event.target as Node)) {
        setIsOpen(false);
        setSearchTerm('');
        onBlur?.();
      }
    };

    document.addEventListener('mousedown', handleClickOutside);
    return () => document.removeEventListener('mousedown', handleClickOutside);
  }, [onBlur]);

  const handleInputChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const newValue = e.target.value;
    setSearchTerm(newValue);
    // Always update parent with the current value (including empty string)
    onChange(newValue);
    setIsOpen(true);
  };

  const handleOptionSelect = (option: string) => {
    onChange(option);
    setSearchTerm('');
    setIsOpen(false);
    onBlur?.();
  };

  const handleKeyDown = (e: React.KeyboardEvent) => {
    if (e.key === 'Enter') {
      setIsOpen(false);
      setSearchTerm('');
      onBlur?.();
    } else if (e.key === 'Escape') {
      setIsOpen(false);
      setSearchTerm('');
    }
  };

  const displayValue = searchTerm || value;

  return (
    <div ref={dropdownRef} className="relative w-full">
      <div className="relative">
        <input
          ref={inputRef}
          type="text"
          value={displayValue}
          onChange={handleInputChange}
          onFocus={() => setIsOpen(true)}
          onKeyDown={handleKeyDown}
          placeholder={placeholder}
          className={`${className} pr-8`}
        />
        <button
          type="button"
          onClick={() => {
            setIsOpen(!isOpen);
            inputRef.current?.focus();
          }}
          className="absolute right-2 top-1/2 transform -translate-y-1/2 text-app-gray-medium hover:text-app-black transition-colors"
        >
          <ChevronDown 
            className={`w-4 h-4 transition-transform duration-200 ${isOpen ? 'rotate-180' : ''}`} 
          />
        </button>
      </div>

      {isOpen && (
        <div className="absolute z-50 w-full mt-1 bg-white rounded-lg shadow-lg max-h-48 overflow-y-auto" style={{ border: '1px solid hsl(var(--app-gray-light))' }}>
          {searchTerm.length < 4 ? (
            <div className="px-3 py-2 text-app-gray-medium text-sm">
              Type at least 4 characters to search
            </div>
          ) : filteredOptions.length > 0 ? (
            filteredOptions.map((option) => (
              <button
                key={option}
                type="button"
                onClick={() => handleOptionSelect(option)}
                className="w-full px-3 py-2 text-left transition-colors text-app-black hover:bg-gray-50"
              >
                {option}
              </button>
            ))
          ) : searchTerm && !searchTerm.match(/\d/) ? (
            <button
              key="other"
              type="button"
              onClick={() => handleOptionSelect("Other")}
              className="w-full px-3 py-2 text-left transition-colors text-app-black hover:bg-gray-50"
            >
              Other
            </button>
          ) : (
            <div className="px-3 py-2 text-app-gray-medium text-sm">
              No matching jobs found
            </div>
          )}
        </div>
      )}
    </div>
  );
};

export default JobSearchDropdown;