import React, { useState, useRef, useEffect } from 'react';
import { ChevronDown } from 'lucide-react';

interface JobSearchDropdownProps {
  value: string;
  onChange: (value: string) => void;
  onBlur?: () => void;
  placeholder?: string;
  className?: string;
}

const JOB_OPTIONS = [
"Software Engineer", "Frontend Developer", "Backend Developer", "Full Stack Developer", "Mobile App Developer", "Web Developer", "Ui Designer", "Ux Designer", "Data Scientist", "Machine Learning Engineer", "Ai Researcher", "Cloud Architect", "Devops Engineer", "Systems Administrator", "Network Engineer", "Database Administrator", "Cybersecurity Analyst", "Qa Engineer", "Game Developer", "Embedded Systems Engineer",
"Technical Writer", "Product Manager", "Scrum Master", "It Support Specialist", "Help Desk Technician", "Doctor", "Nurse", "Licensed Practical Nurse", "Certified Nursing Assistant", "Pharmacist", "Pharmacy Technician", "Paramedic", "Emergency Medical Technician", "Dentist", "Dental Hygienist", "Dental Assistant", "Veterinarian", "Veterinary Technician", "Physical Therapist", "Occupational Therapist",
"Radiologic Technologist", "Medical Assistant", "Surgical Technologist", "Respiratory Therapist", "Home Health Aide", "Barista", "Server", "Cook", "Line Cook", "Prep Cook", "Sous Chef", "Chef", "Pastry Chef", "Food Service Worker", "Waiter", "Waitress", "Host", "Hostess", "Busser", "Dishwasher",
"Caterer", "Food Runner", "Fast Food Worker", "Drive Thru Operator", "Bartender", "Barback", "Delivery Driver", "Pizza Delivery Driver", "Hotel Housekeeper", "Front Desk Clerk", "Hotel Concierge", "Bellhop", "Room Service Attendant", "Valet Attendant", "Casino Dealer", "Casino Host", "Event Coordinator", "Wedding Planner", "Banquet Server", "Club Promoter",
"Tour Guide", "Cashier", "Retail Associate", "Sales Associate", "Stock Associate", "Customer Service Representative", "Customer Service", "Inventory Clerk", "Shelf Stocker", "Store Manager", "Assistant Store Manager", "Greeter", "Bagging Clerk", "Mall Security Guard", "Merchandiser", "Personal Shopper", "Gift Wrapper", "Loss Prevention Specialist", "Taxi Driver", "Ride Share Driver",
"Driver", "Bus Driver", "School Bus Driver", "Truck Driver", "Courier", "Bicycle Messenger", "Forklift Operator", "Warehouse Worker", "Order Picker", "Package Handler", "Logistics Coordinator", "Dock Worker", "Shipping Clerk", "Nanny", "Babysitter", "Daycare Worker", "Preschool Teacher", "Childcare Assistant", "Elder Caregiver", "Housekeeper",
"Cleaner", "Janitor", "Maid", "Pet Sitter", "Dog Walker", "Pet Groomer", "Landscaper", "Gardener", "Pool Cleaner", "Electrician", "Plumber", "Carpenter", "Welder", "Hvac Technician", "Auto Mechanic", "Diesel Mechanic", "Machinist", "Construction Worker", "General Laborer", "Roofing Specialist",
"Painter", "Drywall Installer", "Flooring Installer", "Bricklayer", "Receptionist", "Administrative Assistant", "Office Clerk", "Data Entry Clerk", "File Clerk", "Executive Assistant", "Secretary", "Office Manager", "Virtual Assistant", "Call Center Representative", "Collections Agent", "Telemarketer", "Appointment Setter", "Mailroom Clerk", "Switchboard Operator", "Accountant",
"Auditor", "Bookkeeper", "Tax Preparer", "Financial Analyst", "Budget Analyst", "Loan Officer", "Insurance Agent", "Claims Adjuster", "Bank Teller", "Mortgage Broker", "Investment Analyst", "Payroll Specialist", "Real Estate Agent", "Property Manager", "Teacher", "Teaching Assistant", "Substitute Teacher", "School Counselor", "Principal", "Tutor",
"Librarian", "Library Assistant", "Academic Advisor", "Professor", "Lawyer", "Paralegal", "Legal Assistant", "Court Clerk", "Judge", "Security Guard", "Private Investigator", "Police Officer", "Corrections Officer", "Firefighter", "Manager", "Assistant Manager", "Shift Leader", "Supervisor", "Team Lead", "Freelance Writer",
"Graphic Designer", "Illustrator", "Photographer", "Video Editor", "Voice Actor", "Music Producer", "Social Media Influencer", "Virtual Tutor", "Translator", "Maintenance Worker", "Facilities Technician", "Groundskeeper", "Building Superintendent", "Handyman", "Lifeguard", "Camp Counselor", "Amusement Park Worker", "Theme Park Attendant", "Carnival Worker", "Tour Bus Driver",
"Street Performer", "Festival Staff", "Farm Worker", "Fruit Picker", "City Planner", "Urban Planner", "Building Inspector", "City Clerk", "City Council Member", "Mayor's Assistant", "Public Works Laborer", "Water Treatment Plant Operator", "Waste Management Worker", "Sanitation Worker", "Street Sweeper Operator", "Parking Enforcement Officer", "Meter Reader", "Building Maintenance Worker", "Parks And Recreation Worker", "Recreation Coordinator",
"Community Outreach Specialist", "City Bus Driver", "Transit Operator", "Traffic Engineer", "Civil Engineer (municipal)", "City Electrician", "Zoning Officer", "Public Safety Officer", "Emergency Management Coordinator", "City Attorney", "Planning And Zoning Coordinator", "City Engineer", "City Project Manager", "Permit Technician", "Code Enforcement Officer", "Neighborhood Services Coordinator", "City Grant Writer", "Community Development Specialist", "Animal Control Officer", "Public Health Inspector",
"City Auditor", "Budget Officer", "City Finance Director", "Environmental Compliance Specialist", "City Surveyor", "Municipal Court Clerk", "Recycling Program Coordinator", "Water Quality Technician", "Traffic Signal Technician", "Road Maintenance Worker", "City Arborist", "Crew Member", "Associate", "Team Member", "Helper", "Laborer", "Worker", "Staff Member", "General Worker", "Operator",
"Technician", "Specialist", "Coordinator", "Agent", "Assistant", "Personal Trainer", "Psychiatrist", "", "University Assistant Engineer", "Secretary To Commissioner Of Bldgs", "Executive Asst To The Commissioner", "Sr Community Organization Specialist Urban Renewal", "Elevator Mechanic Helper", "Gasoline Roller Engineer L15", "Captain Detailed As Chief Of Organized Crime Control", "Director Of Policy Analysis", "Deputy Commissioner For Law Enforcement", "Fraud Investigator", "Administrative Blasting Inspector", "Administrative Director Of Residential Child Care",
"Plant Maintainer", "Front Desk / Sales Associate", "Juvenile Counselor", "Special Examiner", "Deputy Controller", "Supervisor Dockbuilder", "Program Producer", "Captain Detailed As Chief Of Training", "Client Advisor / Sales", "Associate Project Manager", "Consulting Engineer", "Bookbinder", "Supervising Probation Officer", "Personnel Director Health Care Facilities", "Dean", "Director Of Advocacy", "Supervising Demolition Inspector", "Supervising Chief Surgeon", "Adm Manager Non Mgrl", "Admin Community Relations Specialist",
"Store Associate", "Assistant Commissioner", "Cashier (truck)", "Cooperative Education Trainee Legislative Clerical Assistant", "Captain Detailed As Chief Of Crime Control Strategies", "Housing Exterminator", "Line Cook / Prep", "Night Attendant", "Speaker/majority Leader", "Director, Research Development And Policy Analysis", "Director Of Management Planning", "Borough President", "Chairman", "Rackets Investigator Start >4 24 08 No Abc", "Deputy Director Of Health And Safety", "Pickup / Delivery Driver", "Associate Dean", "Administrative Storekeeper", "Sr Healthcare Prog Plan Anlyst", "Deputy Chief Of Staff To The Chancellor Ýdoe¨",
"Roofer", "Soft Serve Attendant", "Supervising Computer Service Technician", "Health Services Manager Non Managerial Level II", "Lab Specialist/assistant Reg Sub", "Secretary To The Board Of Correction", "Watershed Maintainer", "Special Commissioner Of Investigation Nyc School Dist. Doi", "School Food Service Manager", "Director Of Research Planning And Policy Analysis", "Cuny Administrator Assistant", "Legislative Computer Support Specialist", "Floor Lead / Supervisor", "Mental Health Therapy Aide (mhta)", "Administrative Parks & Recreation Manager", "Kitchen Team", "Director Of Urban Archaeology", "Agency Attorney Intern", "Assistant Teacher", "Emergency Service Aide",
"Assistant To City Administrator", "Deputy Director Of Management", "Personal Stylist", "Director Of Financing Policy Coordination", "Executive Asst To The Nyc Commission To The United Nations", "Adjunct Professor", "Associate Retirement Benefits Examiner", "Director Borough President's Office Of Administration Queens", "Administrative Public Records Officer", "Department Clerk", "Administrative Printing Services Manager", "Intelligence Research Manager", "Associate Laboratory Microbiologist", "Tax Map Cartographer", "Management Auditor", "Analyst (ib)", "Assistant Chemical Engineer", "Admin Job Opportunity Spec Nm", "Agency Medical Director", "Traffic Enforcement Agent",
"Finance Officer", "Job Training Participant", "Senior Intergroup Relations Officer", "Legislative Fiscal Officer", "Chief Advisor, Public Space Policy", "Administrative Public Information Specialist Nm Former M1/m2", "Psychologist", "Director Of Equal Opportunity", "Rubber Tire Repairer", "Borough Director Of Recreation", "University Professor", "Director Of Security", "Deputy Executive Director Of Financial Operations", "Third Deputy Comptroller", "Cuny Secretarial Assistant", "Admin Landmarks Preservationist", "Confidential Secretary Of Administrative Law Judge", "Principal School Neighborhood Worker", "Spa Specialist", "Curatorial Assistant",
"Director Of Exercises And Training", "Commissioner Of Dept Of Info Technology & Telecommunications", "Assistant To The Deputy Commissioner", "Chief Of Housing Community Activities", "Eoc Assistant", "Senior Supervisor Communication Electrician", "Executive Asst Domestic Violence Hra", "Housing Exterminator Al II & III", "Director Of News Bureau", "Assistant Vice President", "Consultant Public Health Nurse", "Tailor/alterations", "Mortgage Tax Examiner", "Civil Engineer", "Custodial Assistant", "Life Guard", "Superintendent", "Chief Consultant", "Secretary To District Attorney", "Cuny Technical Support Aide",
"Locksmith", "Chief Dockmaster", "Secretary Of Comm", "Deputy Asst Admin For Personnel Adm & Labor Rel", "Risk Management Officer", "Director Of The Mayor�s Office Of Operations", "Fiscal Responsibility Officer", "Director Of Food Stamp Program", "Eoc Custodial Assistant", "Senior Detective Investigator Start >4 24 08 No Abc", "F/t Dc 37 Family Para", "First Deputy Mayor", "Administrative Housing Development Specialist", "Counter/takeaway", "School Computer Technology Specialist", "Pizza Cook", "Chief Administrator Of Impartial Hearing Office", "Deputy Director Of Probation", "Assoc Commissioner For Planning,review And Evaluation", "Substitute Health Svc. Aide",
"Director Of Research & Policy Development", "Case Management Nurse", "Bridge Operator", "Legislative Coordinator", "Probation Officer", "Secretary Of Department", "University Associate Administrator", "Hostler", "Administrative Borough Superintendent", "Associate Engineering Technician", "Teacher General Ed", "Landscape Architect Intern", "Director Of General Services", "Counter / Slice Staff", "Tests And Measurement Specialist", "Director Of Hud Acquired Properties", "City Security Aide", "Executive Assistant To Commissioner Of Transportation", "Lieutenant D/a Special Assignment", "Construction Project Manager",
"Director Of Communications", "Server / Front Of House", "Computer Programmer Analyst Trainee", "Store Manager / General Manager", "Supervisor Of Elevator Maintenance", "Secretary To The Excutive Assistant", "Steam Fitter's Helper", "Secretary To Member", "Chief Financial Officer", "Restaurant Server", "Hearing Examiner", "Psychologist In Train Reg Sub", "Inspector General", "Secretary To The Chair, Landmarks Preservation Commission", "Contract Specialist", "Project Manager", "Collections Unit Head", "Water Use Inspector", "Clerical Associate Most Mayoral Ag", "Secretary To Deputy Commissioner",
"Jewelry Specialist / Watch Specialist", "Administrative Deputy Register", "Admin Dir Of Laboratory", "Director Of Consumer Information", "Investigator Empl Disc", "Climber & Pruner", "Computer Operations Manager", "New Principal Intern", "Bio Medical Equipment Technician", "Environmental Health Technician", "Nurse Practicioner", "Ast Commissioner For Policy And Community Resilience", "Chairman Commission On Human Rights", "Elevator Mechanic", "Legislative Analyst", "Non Teaching Adjunct V", "Associate Air Pollution Inspr", "Secretary To The Deputy Chair", "Kitchen / Prep Cook", "Director Of Bureau Of Consumer Services",
"Director Of Management & Planning", "Education Officer", "Research Projects Coordinator", "Director Of Organized Crime Control Pd", "Principal Administrative Associate Non Supvr", "Clerk To The Board", "Associate Sanitation Enforcement Agent", "Deputy Chief Rackets Investigator", "Director Legal Division/gen Counsel& Spec Counsel", "Program Research Analyst To The Public Advocate", "Executive Assistant For Planning", "Assoc Spvr Of School Security", "Captain Chief Of Staff", "Chief Of Intelligence & Counterterrorism", "Director Of Compliance & Legislative Development", "Scooper / Crew", "Office Assistant", "Guest Service Agent", "Management Auditor Trainee", "Customer Service / Personal Banker",
"Medical Officer", "Spvsg Fad Dep Dir Dsptch Dtail", "Associate Staff Analyst", "Youth Development Specialist", "Supervisor Of Mechanical Installations & Maintenance", "Area Manager Of School Maintenance", "Donation Attendant / Receiver", "Dessert Cook", "Communication Electrician", "Eoc College Lab Technician", "Teach Asst Vocation Reg Sub", "Captain Detailed As Chief Of Patrol", "Principal Administrative Associate Lev 1 & 2 Non Supvr", "Borough Commissioner", "Warehouse Supervisor", "Director Of Public Affairs", "Substitute School Aide", "Deputy Director Of Methods & Analysis", "Guest Services / Front Desk", "General / Store Manager",
"High School Elem Counselor", "Senior Voting Machine Technician", "It Assistant", "Shift Lead", "Deputy Superintendent", "Playground Associate", "Assistant Principal Admin", "Community Assistant", "Attorney Campaign Fin Board", "City Clerk & Clerk Of Council", "Education Analyst Trainee", "Senior Computer Programmer", "Telecommuncation Manager", "12 Month Special Education Asst. Principal", "Housing Assistant", "Senior Service Inspector", "Supervising Fire Marshal", "Director Of Housing Applicantions", "Concessions", "Captain Detailed As Chief Of Special Operations",
"Front Desk Agent", "Director Of Noise Abatement", "Protection Agent", "Admin School Security", "Box Office / Membership Sales", "Project Manager Intern#", "Counter / Retail Associate", "Food Service Administrator", "City Parking Equipment Service Worker", "Assist Commissioner For Policy Analysis & Prog Deve", "Assistant Chief Fire Marshal", "It Security Specialist", "Junior Public Health Nurse", "Director Or Management", "Adm Manager Non Mgrl From M1/m2", "Custodial Supervisor", "Park Supervisor", "Commissioner Of Community Development", "Dep Dir Mtr Eq Mntc", "Director Of Crisis Assistance And Training",
"Assistant To Heo", "Cuny Office Assistant", "Procurment Analyst Level III", "Lead Theatre Technician", "Monuments Officer", "City Dentist", "Landmarks Preservationist", "Third Assistant Marine Engineer", "Repair Crew Chief", "Lot Supervisor", "Staff Audiologist", "Asst Commissioner For Planning & Prg Deve", "Associate Public Health Sanitarian", "Captain: Chief Of Transportation Bureau", "Administrative Graphic Artist", "Senior Deputy Commissioner", "Lecturer", "Higher Education Officer", "Associate Commissioner For Employment Service", "Branch Manager",
"Executive Agency Counsel", "Deputy Director Of Motor Equipment Maintenance", "Kitchen Manager", "Health Services Manager Non Managerial Level I", "Assistant Commisioner", "Administrative Quality Assurance Specialist", "Distinguished Lecturer", "Delivery Driver (franchises Vary)", "Assistant Comissioner For Family Operations", "Associate Urban Designer", "Supervisor Of Mechanics", "Administrative Management Auditor", "F/t School Safety Officer", "F/t Film Inspection Asst.", "Administrative Investigator", "City Register", "Labor Relations Analyst Trainee", "Delivery Driver (some Shops)", "Asst To The Chairman", "Substance Abuse Prevention & Intervention Specialist",
"Urban Archeologist", "Vending Prep", "Assistant Commissioner For Aftercare & Preventive Svcs", "Supervising School Aide", "Legal Coordinator", "Supervisor Of Ironwork", "Adult Educat Teach Reg Sub", "Youth Coordinator", "Inspector Elevators", "Plasterer", "Program Officer", "Director Of Mental Health Disaster Preparedness", "Adjunct College Lab Tech", "Valet", "Catering / Production Support", "Assistant Executive Secretary", "Dockmaster", "Educator / Sales Associate", "Equal Rights Compl Spec", "Personal Banker / Customer Service Rep",
"Teller / Bank Associate", "City Laborer", "Director Of Community Involvement", "Non Teaching Adjunct III", "Assistant Legislative Representative", "Commissioner Of Sanitation", "School Psycholgist", "University Dean", "Assist Commissioner", "Spvsg Fad Dir Dsptch Op Detail", "Director Of Fiscal Operations", "Warden Deputy Warden Ted < 11/1/92", "Commissioner Of Labor Relations", "Physician's Assistant", "Eoc Lecturer/ Doctral Schedule", "Executive Assistant To The Chancellor", "Certified Local Area Network Administrator", "Front Desk / Membership Sales", "Guidance Counselor Assigned A", "Communications Officer",
"Enforcement Officer / Revenue Control", "Secretary To The Commissioner Of Labor Relations", "Deputy Administrator", "Deputy Community Superintendent", "Dir Of Quality & Cost Control", "Administrative Landscape Architect", "Agency Attorney Interne", "Crew / Server", "Secretary To One Deputy Commissioner", "Director, Energy Management Strategy", "Senior Title Examiner", "Secretary To The Comptroller", "Stock Worker", "Asst Commissioner For Agency Preparedness And Response", "Revenue Auditor / Cash Office", "Assistant Chemist", "Director Of Motor Equipment Maintenance Nm", "Maintenance / Porter", "Assistant Superintendent Of Schools", "Plumber's Helper",
"Assistant Counsel Pd", "Housing Assistant Trainee", "Psychiatric Nurse (hourly → Annualized)", "Client Advisor / Boutique Sales", "Commissioner Of Health", "Chief Asset Management Officer", "Agency Chief Decarbonization Officer", "Legislative Project Manager", "Associate Education Officer", "Secretary Of The Commission", "Investment Trustee Deferred Compensation", "Legislative Intern", "Secretary To The Executive Director", "Legislative Financial Analyst", "Educator", "Coach / Instructor", "Director Of Public & Community Relations", "Secretary To Commissioner", "Park Borough Commissioner", "Director Of Program Planning",
"Administrative Tax Auditor", "Director Of Television", "Director Of The Mayor�s Office Of Administrative Services", "Police Administrative Aide", "Customer Service Associate", "Supervising Emergency Medical Service Specialist", "Asst Project Planner", "Architectural Intern", "Medicolegal Investigator", "Dir Of Fiscal Affairs", "Stylist", "Agency Attorney", "Hearing Officer", "Catering Coordinator", "Equal Employment Opportunity Officer", "Member Of The Environmental Control Board Oath", "Exec Asst To The Commissioner Of Finance", "Deputy Commissioner Of Labor Relations", "District Manager", "City Clinician",
"College Aide Assignment Levels II And III", "Director Of Motor Equipment Maintenance", "Assistant Advocate Pd", "Resident Building Superintendent", "Non Teaching Adjunct II", "Purchasing Agent", "Concessions Cashier", "Administrator Of Medical Affairs", "Metal Work Mechanic", "Asst Commissioner For Planning & Program Dev", "Dir Of Personnel & Labor Rels", "Counter/cashier", "Commissioner Of Environmental Protection", "Security Officer", "Director Of Community Relations", "Bridge Painter", "Porter Supervisor (utility Worker Lead)", "Special Assistant To The Deputy Executive Director", "Director, Data Processing Coordination", "Teacher Aide",
"Substitute Ed Para", "Director Of Technology Development Pd", "Director Of Intergovernmental Relations", "Examiner Of Accounts", "Chief Of Strategic Initiatives", "Project Coordinator", "Supervising Rackets Investigator", "Special Assistant To Da", "Facility Manager", "Surveyor", "Cook / Dumpling Maker", "Children's Counselor", "Communications Director", "Senior Project Planner", "Executive Director, Citywide Event Coordination & Management", "Associate Taxi & Limousine Inspector", "Associate Investigator", "Front Desk Associate", "Computer Specialist", "Server/operator",
"Director Of Motor Transport", "Director,citywide Occupational Safety & Health Program", "City Planning Technician", "Supervising Rackets Investigator Start >4 24 08 No Abc", "Supervisor Electrician", "Director Of Motor Equipment", "Sorter", "Community Liaison Worker", "Laboratory Associate", "Systems Administrator Cam Fin Bd", "City Seasonal Aide", "Health Care Prog Plan/analyst", "Community Planning Board Coordinator", "E Commerce / Online Sales Associate", "Director Of Contract Administration", "Criminalist Deputy Director Of Labatory", "Marine Maintenance Mechanic", "Executive Assistant To The Director Of Administration", "Manager, Water And Sewer Systems", "Deputy Mayor",
"Uft School Secretary Assigned Non School Based 12 Month", "Valet Supervisor", "Assistant Principal Custodial Supervisor", "Housekeeping Attendant", "Director Of Support Services Pd", "Administrative Public Health Nurse", "Eoc Mail/message Services Worker", "Director, Medical Affairs", "Cement Mason", "Fire Safety Cadet", "City Deputy Medical Director", "Executive Assistant For Programs & Policy", "City Custodial Assistant", "Deputy Commissioner, Strategic Initiatives", "Assistant Commissioner Of Information Technology", "Member Of The Housing Authority", "Assistant Supervising Chief Surgeon", "Director Of Audits", "Special Assistant To The President", "Capt Det Chief Of The Housing Bureau",
"Institutional Aide", "Election Worker", "Special Advisor To The Director", "Summer Graduate Intern", "Supervising Fm Mgl Det: Chief Of Staff To Fire Comm", "Gelato Maker", "University Assistant Administrator", "Senior Consultant", "Assistant Architect", "Associate Education Analyst", "Blacksmith", "Captain Detailed As Assistant Chief Inspector", "Staff Nurse", "Chief Operating Officer", "Director Of Eeo/contract Compliance", "Mortgage Loan Officer", "Director Of Criminal Justice Planning And Policy Development", "University Architect", "Associate Parking Control Specialist", "Legislative Aide",
"Supervisor Of Stock Workers", "Motor Vehicle Supervisor", "Detective Investigator", "Second Deputy Comptroller", "Chief Of Department", "Secretary To The Chief Actuary", "Admin Tests & Meas Spec", "Senior Mental Health Worker", "Rigger", "Assistant Director Of Forensic Biology", "Deckhand", "Administrative Procurement Analyst Non Mgrl", "Voting Machine Technician", "Front Desk / Customer Service", "Director Of Methods & Analysis", "Assistant Director Of Finance", "School Secretary Reg Sub", "Stenographer To Each Deputy Commissioner", "Usher / Concessions / Box Office", "Eoc Accountant",
"Community Coordinator", "Senior Office Appliance Maintainer", "Sergeantd/a Supervisor Detective Squad", "Pizza Cook / Oven Operator", "Legal Secretary", "Supervisor Bridge Painter", "Director Of Audit And Investigation", "Associate Chief Rackets Investigator", "Assistant Chief Of Department", "Hccs Sr College Lab Tech", "Supervising Emergency Medical Service Specialist Dpty Chiefs", "Supervisor / Manager", "Captain Detailed As Assistant Chief", "Director Of Internal Affairs Pd", "Director Of Equipment", "Home Aide", "Associate Housing Development Specialist", "Adjunct Associate Professor", "Assistant Director", "Supervisor Sheet Metal Worker",
"Special Assistant To Deputy Executive Director", "Psychiatric Nurse Practitioner (pmhnp)", "Dep Commissioner For Community Relations", "Deputy Borough President", "Deputy Chief Information Technology Officer", "Student Legal Specialist", "Food Service Helper", "University Engineer", "Investigator Trainee", "Executive Dir Of Administration", "Secretary To Assistant To President", "Nutrition Consultant", "Executive Director Of Administration", "Assistant Principal", "Director Of Community Planning Boards", "Beauty Advisor (premium Brands)", "Computer Programmer Analyst", "Director Urban Archaeology Lpc", "Assistant Deputy Commissioner", "Prepared Foods Cook",
"Executive Director, Technological Development", "Environmental Police Officer", "Consultant On Race Relations", "Surgeon Detailed As Deputy Chief Surgeon", "Grocery Associate", "Director Of Direct Service Programs", "Asbestos Hazard Investigator", "Gelato Maker / Artisan", "Housing Exterminator Al Iv", "New York City Fellow", "Investment Manager", "Special Assistant To The Human Resources Administrator", "Supervising Communication Electrician", "Cook / Kitchen", "Comptroller", "Grocery Stocker", "Administrative Nutritionist", "Lecturer/doctoral Schedule", "Shift Supervisor", "Valet Attendant (base Wage)",
"Supervisor Painter", "Executive Secretary To The Public Advocate", "Deputy Director Of Communications", "Deli Clerk", "Electrical Engineering Intern", "Masons Helper", "College Lab Technician", "Steam Fitter", "Dishwasher / Kitchen Help", "Adm Manager", "Events / Catering Staff", "Executive Deputy Sheriff", "Supervising Human Rights Specialist", "Dep Dir Of Audit & Prog Analysis", "Cheese Monger", "Director Of Criminal Justice Data Share And Info Servs Qn Da", "Radio And Tevevision Operator", "Supervisor II Social Work", "Fitness Instructor", "Director Of Department Advocates Office",
"Public Health Assistant", "Campus Security Assistant", "Pizza Maker / Coal Oven Cook", "Executive Assistant To The Human Resources Admin", "Supervisor Highway Repairer", "Supervisor Of Bridge Operations", "Confidential Secretary", "Assistant Landscape Architect", "Attendant / Cashier", "Events / Pr", "Cse Chairperson", "Senior It Architect", "Chief Engineer", "Eoc Adjunct College Lab Tech", "Deputy Director Of Cyber Crime Forensics", "Child Protective Specialist Supervisor", "Reporter/ Stenographer", "Supervisor Per Session", "Assistant Professor", "Associate Commissioner For Adult Services",
"Key Holder", "Buyer / Curator", "Scooper/server", "Jr Ph Nurse", "Interpreter/translator Doe", "Captain Detailed As Chief Of Labor Relations", "Head Nurse", "Recreation Specialist", "Urban Park Ranger", "Scientist", "Intelligence Research Specialist Pd", "Front Desk / Membership", "Confidential Examiner", "Chauffeur Attendant", "Assistant Deputy Administrator", "Executive Assistant To The Commissioner", "Senior Vice President", "Assistant Director Of Neighborhood Safety", "Sandwich Artist", "Engineering Technician",
"Confidential Secretary To The Deputy Commissioner", "Custodian Engineer", "Administrative Psychologist", "Police Attendant", "Certified It Administrator", "Chief Actuary", "Attending Physician", "Child Welfare Specialist", "Administrative Procurement Analyst", "Business Research & Data Analytics Specialist", "Quality Assurance Specialist", "Coop Trainee Typist", "Events / Catering Assistant", "Legislative Administrative Secretary", "School Lunch Assistant Cook", "Director Of City Legislative Affairs", "Secretary To Department", "Director Office Of Policy", "Administrative Superintendent Of Highway Operations", "Supervising Bookbinder",
"Mayoral Program Coordinator", "Counsel", "Supervisor Boiler Maker", "Administrative Contract Specialist", "Secretary Of The Tax Commission", "Commissioner Of Transportation", "Ice Cream Maker", "Director Nyc Loft Board", "Civilianization Manager Pd", "Member, Civilian Complaint Review Board", "Personal Banker", "Park Services Worker", "Special Assistant To The Chancellor", "Assistant Director Of Administration", "University Assistant Dean", "Authenticator / Specialist", "Director Of Council Services Bureau", "Legislative Attorney", "Chief Of Professional Standards", "Director Employee Assistance Program",
"Confidential Asst To The Executive Deputy Commissioner", "Special Advisor To The City Clerk", "Director Of Probation", "Transportation Borough Commissioner", "School Social Worker Reg Sub", "Supv Of Housing Exterminators", "Director Of The Mayors Office Of Appointments", "Commissioner Of Department Of Veteran's Services", "Senior Sewage Treatment Worker", "Senior Secretary", "Congreg Care Spec Acs", "Deputy Commissioner", "Mental Health Worker", "Director, Office Of Operations", "Admin Schl Secur Mgr", "Certified It Developer", "Eoc It Support Assistant", "Intelligence Research Manager Pd", "Shift Lead / Supervisor", "Communication Assistant",
"Asst Comm Prgm Dev Revw Hmh", "Commissioner Of Citywide Administrative Services", "Director Of Immigrant Affairs", "Capt Det Chief Of Internal Affairs", "Chief Administrator Of Impartial Hearings", "Press Secretary Ýdoe¨", "School Secretary", "Lot Manager / Site Manager", "Assistant Mechanical Engineer", "Warden Deputy Warden In Comm", "Adjunct Senior College Lab Tech", "Bike Tech / Specialist", "Special Assistant To The First Deputy Commissioner", "Asst Commissioner For Public & Legis Affairs", "Deputy General Counsel", "Concessions / Bar", "Executive Administrator Of Gracie Mansion", "Private Secretary", "Principal Accountant Investigator", "Special Assistant Cannabis Nyc",
"Highways And Sewers Inspector", "Teacher Assistant Reg Sub", "Bartender (concessions)", "Senior Automotive Service Worker", "Special Assistant To The Borough President", "Deputy Counsel", "Adult Ed 35 H", "Houseparent Aide", "Lot Attendant / Cashier", "Deputy Chancellor", "Attendant", "Assistant Sergeant At Arms", "Claim Specialist", "Director Employee Management Division", "Foh Supervisor", "Legal Secretarial Assistant", "Director Of Eeo", "Chemical Engineer", "Captain Detailed As Chief Of Strategic Initiatives", "Secy To The Director Of Collective Bargaining",
"Teacher Attendance Reg Sub", "Associate Chemist", "Picker/packer", "Director Of Information And Research", "Surgeon", "Assistant To The Comptroller", "Ice Cream Maker / Batch Maker", "Director Of Artworks", "Administrative Supervisor Of Skilled Trades", "Special Officer", "Senior Field Supervisor", "Maintenance Technician / Handyman", "Sewage Treatment Worker", "Administrative Retirements Benefits Specialist", "Legislative Information Officer", "Worker's Compensation Benefits Examiner", "Deputy Chief", "Deputy Executive Director", "Mechanical Engineering Intern", "District Manager Of Administration And Business Affairs",
"First Deputy Comptroller", "Director For Equal Employment Opportunity", "Educational Management Associate", "Special Assistant In Mental Retardation", "Counter Cashier", "Teacher Assigned A", "Cuny Broadcast Associate", "Dir Of Healthcare Facilities And Provider Readiness", "Associate Counsel", "Research & Liaison Coordinator", "Makeup Artist / Services", "Research Assistant", "Legislative Administrative Assistant", "Per Session Ed Para", "Director Of Elder Abuse Program Services Qn Da", "Deputy Chancellor Financial Affairs", "Executive Assistant To The Comptroller", "Area Manager", "Special Advisor To City Clerk", "Ombudsman",
"Administrative Chief", "Radio And Television Operator", "Concessions Culinary Supervisor", "Medical Specialist", "Counselor", "Chief Information Technology Officer", "Valet (w/tips)", "Director Of Energy Conservation", "Concourse Supervisor", "Sergeant D/a Special Assignment", "Foster Grandparent", "Senior Administrative Assistant", "Assistant Caretaker", "Associate Park Service Worker", "Staff Analyst Trainee", "Marine Engineer", "Commiss Of The Off To End Domest And Gend Ba Viol", "Assistant To The Public Advocate", "Supervisor Locksmith", "Supervisor Of Housing Stock Workers",
"Instructor", "Catering Manager / Events", "Buyer / Purchasing Specialist", "Stocker", "Front Desk / Reception", "Engineering Work Study Trainee", "Compositor", "Principal Appraiser", "Civil Engineering Intern", "Telecommunications Associate", "Warden Assistant Deputy Warden Ted < 11/1/92", "Commissioner Of Buildings", "Administrative Director Of Social Services", "Computer Operator Manager", "Chief Of Staff", "Director Of Development", "School Medical Inspector", "F/t Group Leader", "P/t Dc 37 Family Para", "Admin Traffic Enfrcmnt Agent",
"Senior Legislative Investigator", "Commissioner Of Emergency Management", "Regional Director Mental Health Mental Retard & Alc Service", "Monitor", "Deputy Counsel Intern", "Chief Strategy Officer/division Ýdoe¨", "Usher / Floor Staff", "Deputy Chief Clerk", "Administrative Superintendent Of Bridge Operations", "Local Instructional Supervisor", "Director Of Medical Assistance Program", "Deputy Commissioner For City Personnel Services", "Physicist", "Chief Office Assistant", "Supervising Blasting Inspector", "Senior Registrar", "College Accountant", "Asst Director Of Intergovermental Rel For City Legist Affs", "Dir Of Operations", "Higher Education Assistant",
"Deputy Executive Director Of Business And Administration", "Mayoral Office Assistant", "Administratiive Taxi & Limousine Inspector", "Product Trainer", "Trainer / Instructor", "Ride / Park Tech", "Director Of Investigations", "Forens Mort Tech Coord Mrt Srv", "Exec Director Of Grants Management And Administration", "Coop Education Trainee Computer Tech Aide/sr", "Commissioner Of Parks & Recreation", "Senior Automotive Specialist", "Housing Consultant", "Consultant", "Associate Director Health Program", "Executive Secretary To City Clerk", "City Elevator Operator", "Helicopter Pilot", "Director Of The City Record", "Chief Strategy Officer",
"F/t Health Service Aide", "Administrative Assistant To Community Education Council", "Administrative School Food Service Manager", "Cooperative Educational Trainee", "Adm Dir Fleet Maint Mgrl Asgmnt", "Asst Pb Hlth Adv", "Principal Legislative Financial Analyst", "Sr Associate Health Program Director", "College Interior Designer", "New York City Urban Fellow", "Senior Press Officer", "Commissioner Of Homeless Services", "Insider", "Dietary Aide", "Legislative Representative", "It Support Assistant", "Pension Investment Advisor", "Heating Plant Technician", "Certified Applications Developer", "Assistant Commissioner For Program Development",
"Director Of Finance", "Office Machine Aide", "Asst Commissioner For Non Secure Detention Juvenile Justice", "Cafe Leader", "City Research Scientist", "Area Supervisor", "Adult Ed 30 H", "Scooper", "Congreg Care Spec Djj", "Parking Attendant", "Campus Public Safety Sergeant", "Executive Assistant To The First Deputy Clerk", "Deputy Inspector General", "Director Of Regional Joint Interest Park", "Deputy Chief City Medical Examiner", "Director Of Building Management", "Film Manager", "Director Of Community Planning Boards Mgl Assign", "Director Of Plant Operations & Maintenance", "Sr Project Planner",
"Administrative Director Of Laboratory", "Substitute Sr. School Lunch Helper", "Hcppa", "Ice Cream Maker / Batch Operator", "Usher / Box Office", "Executive Deputy Commissioner For Mental Hygiene", "Principal Custodial Supervisor", "Fiscal And Policy Analyst", "Medicolegal Analyst", "Assistant Comptroller", "Space Analyst", "Pizza Cook / Maker", "Secretary To Executive Director", "Coach", "Director Of Labor Relations", "Secretary To Deputy Executive Director", "Nurse Practitioner", "Medical Receptionist / Front Desk", "Inspector Plumbing", "School Equipment Maintainer",
"Asbestos Handler", "Superintendent Of Laundries", "Recreation Supervisor", "Director Bureau Of Weights And Measures", "Director Of The Mayor�s Office Of Appointments", "Public Relations Assistant", "Principal Multiple Dwelling Specialist", "Nutritionist", "Deputy Assistant Chief Of Department", "School Crossing Guard", "Insurance Advisor", "Director, Office Of Administration", "Confidential Asst To The Executive Dir", "Secretary To The Deputy Boro President", "Spvsg Fad Asst Commiss Detail", "Associate Arts Programs Specialist", "F/t School Aide", "Traffic Device Maintainer", "Personal Stylist / Sales Professional", "Deputy Director Of Administration",
"Eoc Adjunct Lecturer", "Registered Nurse", "Psychiatrist (emergency Dept.)", "Emergency Medical Specialist Trainee", "Coordinator Of Criminal Justice", "Assistant Commissioner Of Labor Relations", "Supervisor II", "Telecommunications Specialist", "Donation Attendant", "Computer Associate", "Machinist's Helper", "Emergency Preparedness Manager", "Council Member", "Desk Associate", "Assistant To The President", "Principal Administrative Associate", "Director Of Management Design", "Executive Assistant To The City Clerk", "Architect", "Capt Det Chf Spec Operations M",
"Administrative Construction Project Manager", "College Security Specialist", "Project Planner", "Front Desk / Desk Associate", "Secretary To The Deputy Chancellor", "Guidance Counselor", "Associate Water Use Inpector", "Adm Dir Fleet Maintenance Nm", "Research And Liaison Coordinator", "Warden Deputy Warden In Comm Ted < 11/1/92", "Executive Assistant To The Commissioner Of Employment", "Director Of School Safety", "Housekeeping Manager", "Research And Liaison Specialist", "Health Services Manager", "First Assistant To The Public Advocate", "Site / Store Manager", "Senior Administrator", "Program Specialist Correction", "Special Deputy Comptroller",
"Decedent Property Agent", "New York City Public Service Fellow", "Supvsng Systems Analyst", "Child And Family Specialist", "Boiler Maker", "Director", "Superintendent Of Water And Sewer Systems", "Coordinator, Tenant Patrol", "Rackets Investigator", "Admin Job Opor Spec Managerial", "Maintenance Technician", "Donation Specialist / Pickup Driver", "School Social Worker", "Assistant To Deputy Comptroller", "Research Projects Coord", "It Project Specialist", "Secretary To The Counsel To The Chancellor", "Stationary Engineer", "City Assessor", "Assistant Commissioner For Facilities Development & Const",
"Spec Consultant", "Executive Director Of Gracie Mansion", "Business Promotion Coordinator", "Corporation Counsel", "Legislative Policy Analyst", "Special Asst To Exec Dir", "Special Assistant To The Director", "Senior Cook", "Disability Accommodations Specialist", "Assistant Accountant", "Gasoline Roller Engineer", "Senior Estimator", "Job Opportunity Specialist", "Research Analyst To The Public Advocate", "Assistant Commissioner Of Operations", "Server / Waitstaff", "Deputy Assistant Commissioner For Evaluation", "Asst Dir Of Intergvnmental Reltns For The Albany Office", "Executive Director Of Standards And Appeals", "Executive Director, New York City Loft Board",
"Social Worker", "Assistant Printing Press Operator", "Administrative Assistant To The Mayor", "Associate School Food Service Manager", "Administrative Program Officer", "Confidential Investigator", "College Graph Designer", "College Print Shop Specialist", "Supervisor Ship Carpenter", "Procurment Analyst Level Iii, Oj", "Public Records Aide", "Dep Dir Of Social & Comm Serv", "Deputy Executive Director Campaign Finance Board", "Director Of Community Assistance Unit", "Associate Commissioner For Personnel Service", "Director Of Correctional Standards Review", "Director Of Crim Justice Data Share And Info Servs Kda", "Customer Information Representative Ma L 1549", "Box Office / Ticket Seller", "Senior Advisor For Investigations",
"College Security Director", "Commissioner Of Department Of Veterans Services", "Planner: Production Cntrl & Scheduling", "Capt Det Chief Of The Transit Bureau", "Concessions / Attendant", "Legislative Investigator", "Commissioner Of The Ofc To End Domstc And Gend Based Violce", "Warden Assistant Deputy Warden", "Agency Deputy Medical Director", "Emergency Prepardness Manager", "Lead Attendant", "Ice Cream Maker / Pastry Cook", "Confidential Assistant To Boro President", "Delivery Driver / Runner", "Telecommunications Manager", "Highway Repairer", "Assistant To Commissioner", "Consumer Advocate", "Concessions Warehouse Associate", "Supervisor Of Office Machine Operations",
"University Associate Dean", "Director Of Leased Housing", "Administrative Attorney", "Homemaker", "Deputy Administration Assistant", "Commissioner Of Children's Services", "Counsel To The Mayor", "Sanitation Enforcement Agent", "Transportation Inspector", "Executive Chief Of Staff", "Emergency Medical Specialist Paramedic", "Commissioner Of Business Services", "Advisor For Gay, Lesbian, Transgender Issues", "Director Of Planning", "Geek Squad Agent", "Director Of Information Systems", "Front Desk / Member Services", "Administrative Architect", "Director Criminal Justice Data Share And Info Services", "Supervisor Thermostat Repair",
"Special Assistant To Member Of The Board Of Education", "Eoc Administrative Assistant", "Chauffer Attendant", "Director Of Review & Counseling", "Administrative Real Property Manager", "Student Aide Vocational", "Director Of Criminal Justice", "Project Director", "Assoc Water Use Inspector Mgrl", "Commissioner Of Finance", "Press Officer", "Supervisor Glazier", "Director Borough Improvement Board", "Deputy Director Finance", "Visual Merchandiser", "Water Treatment Plant Operator L2 & 3", "Medical Investigator", "Shuttle Driver", "Eoc Office Assistant", "Puppeteer",
"Eligibility Specialist", "Summer College Intern", "Chief Clerk", "Exec Asst To The Deputy Commissioner", "General Inspector", "Mariner", "Chair Landmarks Preservation Commission", "Supervisor Of Radio Repair Operations", "Admin Contract Specialist", "Senior College Lab Tech", "Special Advisor To The Mayor For Health Services", "Deputy Director Of Design", "Adm School Security Manager U", "Chief Investigating Accountant", "Administrative Accountant", "Executive Director To The Environmental Control Board", "Investment Banking Analyst (entry)", "Associate Fire Protection Inspector", "Administrative Education Officer", "President",
"Administrative Horticulturist", "Program Coordinator", "Education Assistant", "Director Management Information Systems", "Supervising Police Communications Technician", "Assistant To Police Commissionor", "Rn Staff Nurse (hourly → Annualized)", "Merchandise Supervisor", "Counsel To The Police Commissioner", "Executive Director", "Environmental Engineering Intern", "Senior Housekeeper", "Executive Director Of Healthcare Systems Readiness", "Clinical Professor", "Director, Nyc Art Commission", "Deputy Chief Of Operations", "Educational Administrator", "Supervisor Assigned", "Maintenance", "Operations Communications Specialist",
"Landscape Architect", "Public Health Epidemiologist", "Fire Marshal", "Administrative City Planner", "Housing Development Specialist Trainee", "Construction Laborer", "Caretaker", "Buyer", "Projectionist / Av / Programmer Tech", "Bellman/doorman", "Secretary To Community School Board", "New York City Urban Planning And Design Fellow", "Director, Public Affairs And Communication", "Deputy Auditor General", "Correction Administrative Aide", "Secretary To The Fire Commissioner", "Hearing Director", "Admin Schl Secur Mgr Mgl", "Administrative Community Relations Specialist", "Secretary To Conflicts Of Interest Board",
"Eoc Custodial Supervisor", "Business Data And Reporting Analyst", "Computer Aide Non Spvr", "Usher / Seasonal Usher", "Administrative Staff Analyst", "Associate Call Center Representative Non Spvr", "Asst Dir Of Intergvnmentl Relatns For The Washngtn Off", "Secretary To The Chairperson", "Captain Detailed As Chief Of Risk Management", "Computer System Manager", "Mayor", "Actuarial Specialist Level Ii, Oj", "Associate Traffic Enforcement Agent", "Sr College Laboratory Tech", "Director Of Admin", "Executive Cook", "Director Of Internal Auditing", "Teller / Branch Ops", "Spa Therapist", "University Assistant Architect",
"Executive Assistant To The Executive Deputy Adm", "Certified Database Administrator", "Assistant Executive Director", "Associate Administrator", "Director Of Budget Studies & Economic Research", "Assistant Electrical Engineer", "Attending Dentist", "Secretary To The Special Commissioner Investigation Nyc Sch", "Fire Alarm Dispatcher", "Apprentice Inspector", "Aspiring Principal", "Secretary Of The Authority", "Captain Detailed As Chief Of Detectives", "Assistant Captain", "Senior Police Administrative Aide", "District Supervisor", "Cuny Start Instructor", "Secretary To The Special Commissioner Of Investigation Nyc", "Assoc Inspector", "Inspector Hoists And Rigging",
"Medical Record Librarian", "Physician", "Controller", "Supervisor Plumber", "Director Of Race Equity Strategies", "Assistant Highway Transportation Specialist", "Director Of Forensic Biology", "Precinct Community Relations Aide", "Deputy Director Of Community Planning Boards", "12 Month Special Education Supervisor", "Special Consultant", "Delivery Driver (if Used)", "Deputy Director Of Admin Worker's Comp Benefits", "Interpreter", "Psychologist In Training", "Senior Custodial Supervisor", "School Psychologist Reg Sub", "Evidence And Property Control Specialist", "Commissioner Designated As Vice Chairman", "Attorney At Law",
"Procurement Analyst", "Public Service Interne", "Lieutenant", "Assistant Deputy Commissioner Ss", "Prep / Smoked Fish", "Key Holder / Lead", "Supervisor Bridge Repairer And Riveter", "Secretary To The Executive Director Of Retirement System", "Supervisor Roofer", "Executive Director Of Materials For The Arts", "Arts Program Specialist", "Facility Supervisor", "Counsel To The Borough President", "Assistant District Attorney", "Cuny Custodial Assistant", "City Chief Decarbonization Officer", "Deputy Unit Chief", "Senior Bookseller", "Secretary To The Commissioner Of Bldgs", "Public Health Preventative Medicine Resident",
"Principal Nutrition Consultant", "Repair Crew Worker", "Chief Administrative Supt Campus B/g", "Assistant College Security Director", "Client Service / Branch", "Sr Systems Analyst Edp", "Senior Management Consultant", "Highway Transportation Specialist", "Deputy Director Of Equal Opportunity", "Senior Adminisrator", "Assistant Housekeeper", "Stenographic/secretarial Associate", "Associate Juvenile Counselor", "Information Systems Aide", "Secretary To The Commissioner Of Ddc", "Senior Institutional Trades Instructor", "Deputy Assistant Director", "Precinct Receptionist", "City Collector", "Membership Consultant / Sales",
"Helicopter Mechanic", "Senior Rackets Investigator", "Scooper / Counter Staff", "Electrical Engineer", "General Manager", "Deputy Regional Superintendent", "Valet (base)", "Assistant To The Commissioner", "Senior Adviser To The Commissioner", "College Print Shop Coordinator", "Police Officer D/a Detective 2nd Gr", "Server / Bartender (tipped)", "Agency Attorney Dc37", "Deputy Director Legal Division", "Investigative Manager", "Senior Advisor To The Mayor", "Executive Assistant To The First Deputy City Clerk", "Sales Associate / Cashier", "Legislative Assistant", "Director Of Clinical Laboratories",
"House Manager", "Director Of Technical Services", "Systems Analyst", "Chief Fire Marshal", "Supervisor Of Housing Caretaker", "Director Of The Office Of Collective Bargaining", "Administrative Sanitation Enforcement Agent", "Public Health Education Trainee", "Disability Coordinator", "Dir Of Contract Mgmt & Intergovernmental Relations", "Principal Park Supervisor", "Automotive Specialist", "Principal Investigator", "Coordinator Of Veterans' Affairs", "Sorter / Donation Processor", "Public Relations Officer", "Chief, Publications & Reports", "Legislative Support Service Coord", "Jewelry Specialist", "Associate Inspector",
"General Counsel", "Crane Operator Ampes", "Director Of Management Information Services", "Instrumental Specialist Trainee", "Director Of Social Services", "Borough Manager, Office Of Neighborhood Safety", "Deputy Asst Commissioner For Program Dev & Anal", "Associate Human Rights Specialist", "Substitute School Lunch Helper", "Chief Of Student Pathways Ýdoe¨", "Adjunct Assistant Professor", "Senior General Deputy Manager", "Director Of The Mayors Office Of Operations", "Secretary To The Department", "School Lunch Aide", "Analyst", "Beauty Advisor / Sales", "Administrative Actuary", "Assistant Superintendent", "Printing Press Operator",
"Deputy Administrator/comsnr Dos", "City Medical Examiner", "Director Of The Ombudsman Program", "Examining Attorney", "It Service Management Specialist", "Captain Detailed As Chief Of Interagency Operations", "Psychiatric Nurse (estimate)", "Secretary To The Commissioner Of Correction", "Mortgage / Loan Officer", "Pizza Maker", "School Business Manager", "Executive Assistant And Counsel To The Public Advocate", "Supervisor Of Electrical Installations & Maintenance", "Public Relations Adviser", "Pizza Maker / Cook", "Administration Public Record Officer", "Child Protective Specialist", "Loss Prevention", "It Automation And Monitoring Engineer", "Cashier / Pay Station Operator",
"Environmental Police Officer Managerial", "Secretary Of Commissioner", "Lab Specialist/assistant", "Statistician", "Psychiatric Nurse Practitioner (per Diem; Hourly → Annualized)", "Deputy Commissioner Film Office", "Deputy Director Of Emergency Management", "Adm Traffic Enfrcmnt Agent Director Of Parking Enfrcmnt Dist", "Food Prep (concessions)", "Associate Labor Relations Analyst", "Laboratory Helper", "Director Of Interagency Planning", "Distinguished Professor", "Assistant Director Of Education", "Vice President", "Technical Systems Manager", "Blacksmith's Helper", "Assistant Secretary To The Comptroller", "Guidance Counselor Reg Sub", "Senior Salvage Appraiser",
"Deputy Borough Commissioner", "Equal Rights Compliance Specialist", "Coordinator, Voter Registration Activities", "Agency Security Director", "Chief College Lab Technician", "Captain Detailed As Chief Of Operations", "Administrative Associate", "Dough / Prep", "Admin Traffic Enf Agnt Union", "Chief Marine Engineer", "Retail Sales", "School Lunch Helper", "Agency Chief Contracting Officer", "Manager Of Radio Repair Operations", "Assistant Director Of Intergroup Relations", "Associate Director, Office Of Neighborhood Safety", "Pizza Cook / Oven", "Cuny Art Model", "Teacher Assigned B", "Executive Director Of Fleet Operations",
"Director Of Headstart Program", "Employee Assistance Program Specialist", "School Psychiatrist", "Director Of Purchase", "Asst Commissioner", "Research Scientist", "Assistant Administrator Of Public Affairs", "Assoc Supvr Of Schl Sec", "Tech Associate", "School Lunch Loader And Handler", "Labor Relations Trial Examiner", "Research Assistant Behav Sci", "Supervising Fire Alarm Dispatcher", "Carriage Upholsterer", "Special Assistant To The District Attorney", "Probation Officer Trainee", "Supervisor III Social Work", "Paralegal Aide", "Captain Chief Of Counterterrorism", "Housing Development Specialist",
"Supervisor Of Investigators", "Electrician's Helper", "Executive Assistant To The Deputy Commissioner", "Repair Shop Manager", "Senior Repair Crew Chief", "Public Advocate", "Correctional Counselor", "Director Of Biodetection And Response", "Lead Abatement Worker", "Executive Director, Special Projects & Community Events", "School Secretary Per Session", "P/t School Aide", "Customer Service / Counter Rep", "Deputy Comptroller", "Salon Manager", "Secretary To The Commissioner", "Assistant Laundry Supervisor", "Captain Chief Of Community Affairs", "Recreation Director", "Secretary To The First Assistant Corporation Counsel",
"Title Examiner", "University Payroll Analyst", "Administrative Assessor", "Televison Equipment Operator", "Dockbuilder", "Front Desk / Guest Services", "Pilot", "Senior Baker", "Police Officer D/a Detective 1st Gr", "Visitor Services Associate", "Director Of Management Planning Ss", "Legislative Counsel", "Higher Education Officer/asst Administrator", "Deputy Assistant Commissioner", "Admin Housing Development Spec", "Assistant Commissioner, Citywide Pymt Svcs & Stnds", "Wiper", "Admissions Associate", "Assistant Purchasing Agent", "Clerical Aide",
"Assistant Director Of Legal Services", "Administrative Education Analyst", "Associate Urban Park Ranger", "Assistant Commissioner For Labor Relations & Admin", "Non Teaching Adjunct I", "Baker / Dough Prep", "Legistative Manager Office Of Communication", "City Tax Auditor", "Real Property Manager", "City Veterinarian", "Teacher Reg Sub", "Retail Staff", "Non Teaching Adjunct Iv", "Eoc Higher Education Assistant", "Certified Wide Area Network Administrator", "Estimator", "Clerical Associate", "Personnel Program Developement Specialist", "Letterer And Sign Painter", "Secretary To The Human Resources Administrator",
"New Leader", "Director Of The Office Of Correspondence", "Sergeant", "Education Program Facilitator", "Media Services Technician", "Pre Ses Ed Para", "Exterminator", "Supervisor Of School Security", "Executive Legislative Secretary", "Director Of Investments", "Director Of Invest Accounting And Econ Crimes Investigation", "Assistant To The Commissioner Of Parks And Recreation", "Dietitian", "Senior Systems Analysts", "Auto Body Worker", "Commissioner, Un & Consular Corps Diplomatic Relations", "School Medical Inspector Per Session", "Facilities Coordinator", "Administrative Juvenile Counselor", "Commissary Manager",
"Telephone Service Technician", "Adjunct Lecturer", "Associate Professor", "Director Of Investigative Audits", "Administrative Labor Relations Analyst", "Food Service Manager", "Coordinating Manager", "Education Analyst", "College Print Shop Assistant", "Deputy Commissioner For Policy And Analysis", "Forensic Mortuary Technician Coord Of Mortuary Services", "Associate Director Of Nursing Services", "Concessions Cook", "Confidential Secy", "Districting Commission Administrative Assistant", "Substitute School Guard", "Strategic Initiative Specialist", "Temporary Clerk", "Buyer / Vintage Specialist", "Quality Assurance Specialist Trainee",
"Supervisor Of Traffic Device Maintainers", "Coordinator, Election Day Operations", "First Deputy Commissioner", "Executive Assistant To The Director", "Assistant Retirement Benefits Examiner", "Director Of The Office Of Criminal Justice", "Deputy Director Of Management & Budget", "Franchise Manager", "Associate Correctional Counselor", "Spa Attendant", "Strategi Initiative Specialist", "Community Liaison Representive", "Supervisor Plasterer", "Public Information Officer", "Director Of Legislative Coordination", "Commissioner", "Sergeantd/a Special Assignment", "Licensed Barber", "Family Pub Health Nurse", "Executive Director Of Public And Private Partnerships",
"Director Of Health Care Program Planning/analysis", "Motor Vehicle Operator", "School Plant Manager", "Director Of Psychological Services", "City Park Worker", "Server (tipped)", "Fire Protection Inspector", "Community Associate", "Floor Staff (usher/concessions/box Office)", "Counsel To Minority Leader", "Sign Language Interpreter 1,2,3 10m", "School Neighborhood Worker", "Sales / Client Associate", "Front Desk", "Associate Contract Specialist", "Captain D/a Deputy Chief", "Kitchen / Line Cook", "Legislative Administrative Manager", "Loan Officer / Mortgage Specialist", "Chief Of Staff To The Mayor",
"Investigator", "Maintenance / Janitorial", "Senior Student Legal Specialist", "Field Investigation Specialist", "Executive Assistant To The Director Of Management & Budget", "Associate Public Information Specialist", "Operations Manager", "Geologist", "Director Of The Office Of Immigrant Affairs", "Administrative Inspector", "Deputy Commisioner", "College Aide", "It Infrastructure Engineer", "Appraiser", "Regional Instructional Superintendent", "Director Of The Office For People With Disabilities", "Chief Caretaker", "Bridge Repairer And Riveter", "Secretary Of The Department", "Calendar Assistant",
"Laboratory Microbiologist", "Fire Cadet", "Floor / Shift Lead", "Director Of Nyc Medical Reserve Corps", "Assistant To The Mayor", "Sr Management Consultant", "Administrative Manager", "College Accounting Assistant", "Senior Medical Specialist", "Plan Examiner", "Deputy City Sheriff Non Spvr", "Sign Language Interpreter", "Councilmanic Aide", "Director Office Of Communications", "Horseshoer", "Supervising Housing Groundskeeper", "Teacher Trainer", "Counsel To The Public Advocate", "Mate", "Assistant To The Deputy Mayor",
"Human Resources Technician", "Assistant Branch Manager", "Case Mgmt Nurse", "Administrative Fire Protection Inspector", "Oil Burner Specialist", "Chief Of Staff Mayor's Office", "Sergeant D/a Supervisor Detective Squad", "Membership Consultant", "Instructor (cycling/class)", "Assist Commissioner For Intergovernmental Relations", "Director Of Operations", "Executive Secretary", "Press And Speech Aide", "Principal Fingerprint Technician", "General Superintendent", "Guest Services Agent / Representative", "Supervising Public Health Adviser", "Assistant Comptroller Of It", "Director Of Administration", "Environmental Engineer",
"Associate Fraud Investigator", "Supervisor Of Child Care", "Battalion Chief", "Commissioner Of Cultural Affairs", "Council Member Aide", "Secretary To The Chair", "Supervising Dockmaster", "Legislative Messenger", "Principal Investment Officer", "Deputy Chief Technology Officer", "Service Team", "Adult Education Teacher", "Director Of Crime Strategies And Analysis", "Captain Detailed As Chief Of Personnel", "Peer Counselor", "Benefits Opportunity Specialist", "Concessions Cashier / Customer Service Associate", "Public Health Adviser", "Supervising Inspector General", "Cooperative Education Trainee Seasonal Park Help",
"Senior Stationary Engineer", "Special Assistant District Attorney", "Adm Traffic Enfrcmnt Agent", "Administrative Law Judge", "University Administrator", "Lmsw", "Deputy Director Of Medicolegal Investigations", "Public Records Officer", "Registration Staff", "Higher Education Associate", "X Ray Technician", "Nurse's Aide", "Legislative Systems Manager", "Director Of Management & Budget", "Supervising Special Officer", "Research Liaison Adn Governmental Coordinator", "Assistant Environmental Engineer", "Staff Assistant", "Pharmacy Tech", "Special Assistant To The Mayor",
"Special Assistant To Commissioner", "School Safety Agent", "Assistant Commissioner For Facilities Operations", "Prep / Line", "Sergeant At Arms", "Dep Dir Of Program Planning", "Key Holder / Senior Sales", "Maker", "P.o. Da Det Gr3", "Legislative Programmer/analyst", "Ship Carpenter", "Teacher Special Education Reg Sub", "Coop Education Trainee Computer Tech Aide/jr", "Dir Of Investigative Acctng And Economic Crimes Invstngs", "Police Surgeon", "Chief Service Officer", "Traffic Enforc Agent", "Senior Rackets Investigator Start >4 24 08 No Abc", "Apprentice", "Administrative Probation Officer",
"Correction Officer", "Criminalist", "Director Of Audit And Program Analysis", "Assistant Civil Engineer", "Administrative Assistant To The Comptroller", "Director Of Training", "Director Of Land Use Division", "Teacher Special Ed", "Confidential Assistant To The Comptroller", "Commissioner Of Design & Construction", "Counter/cashier / Takeaway", "Projectionist / Av Tech", "Director Of Community Participation Programs", "Emergency Preparedness Specialist", "Watchperson", "Delivery Driver (where Offered)", "City Debris Remover", "Director Of Parent Involvement", "Analyst (ib/sales)", "Educational Administrator Csa",
"Supervisor Carpenter", "Store Leader", "Clock Repairer", "Administrative Business Promotion Coordinator", "Employee Health Benefits Program Director", "Registered Nurse (hourly → Annualized)", "Supervisor Of Traffic Device Maintainers Level 1 Only", "Captain", "Administrative Claim Examiner", "Substitute Principal", "Store / Ops Manager", "Senior Physical Therapist", "Seasonal Associate", "Annual Ed Para", "Executive Deputy Administrator", "Administrative Energy Conservation Specialist", "Kitchen Team / Pizza Maker", "Associate Job Opportunity Specialist", "University Engineer Tech", "Assistant Dean",
"City Mortuary Technician", "Chief Diversity Officer Ýdoe¨", "Crime Analyst", "Public Administrator", "Director Of Public Relations", "Administrative Project Director", "Director Of Neighborhood Conservation", "Motor Grader Operator", "Director Of Tenant & Community Affairs", "Assistant To The Chairman", "Director For Equal Employement Opportunity", "Deputy Commissioner Of Investigations", "Student Legal Assistant", "Multiple Dwelling Specialist", "Medical Director", "Warden Deputy Warden", "Administrator", "P.o. Det Spec", "Adm School Security Manager", "Elevator Operator",
"Valet Attendant (base)", "Director Of Information Services", "Election Trainer", "Executive Director Of Professional Development", "F/t School Lunch Helper", "Principal Police Communication Technician", "Actuarial Specialist Level I", "Assistant Dir Of Administration", "Manager / Foh Lead", "Client Advisor / Luxury Sales", "Supervisor Of Motor Transport", "Front Of House Supervisor", "Auto Machinist", "Pipe Caulker", "Jewelry / Watches Specialist", "Education & Vocat Counselor", "Administrative Director Of Marine Maintenance", "Senior Systems Analyst", "Principal Planning Consultant", "Cleaner / Janitor",
"Criminalist Director Of Laboratory", "Shift Manager", "Key Holder / Shift Lead", "Lot Associate", "Senior Occupational Therapist", "Administrative Engineer", "Admin Traffic Enf Agnt", "Admin Construction Project Manager", "Senior Policy Advisor", "Exec Sec To Advisory Bd For Locational And Extension Educ", "Executive Director Of Food Services", "Economist", "Executive Assistant To The Chief Administrative Law Judge", "Director Correspondence Services", "Dir Of Administration, Worker's Comp Benefits", "School Psychologist", "Property Clerk", "Client Advisor", "Chief Of Staff To The Deputy Chancellor Ýdoe¨", "Secretary To The First Deputy Commissioner Pd",
"Fitting Room Attendant", "Associate Director Operational Services", "Marine Electronics Technician", "Incinerator Facility Manager", "Capt Det Chief Of Department", "Electricians Helper", "Cyber Security Analyst", "Assistant Director Health Program", "Confidential Asst Office Of District Attorney, King County", "Eoc Assistant To Heo", "Field Supervisor", "Supervising Deputy Sheriff Al 1 Only 40 Hr", "Dep Dir Research & Pol Develp", "Customer Service Rep", "Financial Advisor", "Secretary To Dept Chancellor", "Projectionist / Av", "Computer Aide", "Assistant City Assessor", "Eoc Higher Education Officer",
"Exec Asst To The Deputy Com For Citywide Personnel Svcs Dcas", "Police Cadet", "Senior Staff Officer", "Telecommunication Manager", "Director Of Urban Park Ranger Program", "Senior Detective Investigator", "Executive Assistant Midtown Enforcement", "Correctional Standards Review Specialist", "Chancellor", "Energy Conservation Specialist", "Manager, Water Supply", "Director Of Stores", "Deputy Director Of Housing Applicants", "Marine Oiler", "Truck Operator/server", "Human Rights Specialist", "Human Resources Administrator", "Prinicipal Human Rights Specialist", "Sanitation Compliance Agent", "Lot Manager",
"Public Health/preventive Medicine Resident", "Service Inspector", "Secretary To The Chancellor", "Continuing Education Teacher", "Administrative Housing Manager", "Legislative Clerk", "Executive Assistant To The President Of The Tax Commission", "Sheet Metal Worker", "Supervisor Steamfitter", "Admin Asst Campaign Fin Board", "Associate Quality Assurance Specialist", "Director Of Alt Sentencing And Offender Re Entry Progs Qn Da", "Executive Assistant To The Chairman", "Senior Legislative Policy Analyst", "Senior Legislative Financial Analyst", "Computer Service Technician", "Associate Benefits Opportunity Specialist", "Fire Medical Officer", "Bellman/concierge", "Real Property Assistant",
"F/t School Guard", "Water Treatment Plant Operator L1", "Assistant Director Of Toxicology", "Executive Legislative Coordinator", "First Deputy Commissioner General Counsel", "Counsel To The Board", "Caseworker", "Assistant District Manager", "Chief Administrator Supt Campus B/g", "Chaplain", "Chief Of City Sheriff Operations", "Director Of Social & Community Services", "Custodian", "Senior Game Advisor", "Director Of Countermeasures And Response", "Butcher", "Scooper / Server", "Maintenance / Grounds", "Emergency Medical Specialist Emt", "Associate Director, Borough Improvement Board",
"Wealth / Financial Advisor", "Supervising Accountant Investigator", "Front Desk / Operations", "Visitor Services", "Admin Inspector", "Teacher Of Library", "Automotive Service Worker", "Assistant Administrator", "Supervisor Of Radio And Television Operators", "Assoc Adm For Purchasing Materials Mgt & Envir Control", "Special Commissioner Of Investigation Nyc School District", "Eoc Accounting Assistant", "Jr Phnurse", "Substitute Recreation Assistant", "Chief School Business Executive", "Chemical Engineering Intern", "Assistant Chief Racket Investigator", "Nycaps Process Analyst Manager", "Special Assistant To The Fire Commissioner", "Deputy Public Administator",
"Ferry Terminal Supervisor", "Housing Caretaker", "Commissioner Of Housing Preservation & Development", "Director Of Public Health Emergency Evaluation", "Community Supertindent", "Deputy Director Of Security", "Cook / Line", "Administrative Consultant", "Assist Coordinating Manager", "Department Supervisor", "Intelligence Research Specialist", "Associate Commissioner For Management", "Supervising Housekeeper", "Director Of Scheduling", "Executive Inspector", "Port Marine Engineer", "Computer Systems Manager", "Safety Specialist", "Assistant Advocate", "Resident Physician",
"Principal Title Examiner", "Secretary To The Chairman", "Dir Of Materials Management", "Traffic Enforc Agent L 3 & 4 Only", "Director Of Public Information", "Parking Control Specialist", "Deli Worker", "Director Of Neighborhood Park Restoration", "Senior Photographer", "Director Of Office For People With Disabilities", "Confidential Assistant To The Commissioner", "Captain Managerial Details", "Furniture Maintainer", "Housing Stock Worker", "Site Manager", "Assistant Urban Designer", "Eoc Higher Education Associate", "Administrative Space Analyst", "Supervisor III", "Deputy Chief Surgeon",
"Chief Pension Investment Advisor, Finance", "Security Staff", "Deputy Director Of Headstart Program", "Principal Assigned", "Associate Youth Development Specialist", "Program Evaluator", "Deputy Director Office Of Communications", "Traffic Enforcement Agent Al 1 & 2 Only", "Student Aide", "Senior Accountant Investigator", "Assistant Transportation Specialist", "Instructor / Coach", "Administrative Project Manager", "Chief Of Staff To First Deputy Commissioner", "Instrumental Specialist", "Glazier", "Executive Program Specialist", "Director Of Public And Community Relations", "Administrative Transportation Coordinator", "Chief Service Officer Of Nyc Service",
"Director Of Mortgage Research And Analysis", "Group Fitness Instructor", "Financial Advisor / Wealth Associate", "Lot / Truck Attendant", "Senior Executive Director Of Intergovernmental Affairs Ýdoe¨", "Special Assistant", "Deputy Commissioner Of It", "Administrative Housing Superintendent", "Collections Specialist", "First Assistant Corporation Counsel", "Associate Commissioner", "Associate Real Property Manager", "Special Assistant To The Executive Director", "Confidential Agency Investigator", "Sorter / Pricer", "City Service Aide", "Retail/thrift Associate", "City Medical Specialist", "Secretary To The Corporation Counsel", "F/t Sr. School Lunch Helper",
"Deputy Chief Of Staff", "Senior Executive Secretary", "Market Agent", "Chief Lifeguard", "Director Of The Mayors Office Of Administrative Services", "Pizza Baker / Oven", "Section Lead", "School Medical Inspector Reg Sub", "Director Of Property Management", "Deputy Operation Support Manager", "Deputy Assistant Counsel", "Confidential Strategy Planner", "Jewelry Specialist / Gemologist", "Private Banking / Wealth Associate", "Personal Trainer / Instructor", "Computer Operator", "Supervising Hull & Machinery Inspector", "Associate Operations Communications Specialist", "Dir Of Audit & Prog Analysis", "Adm Manager Non Mgr",
"Mail/message Services Worker", "House Manager / Supervisor", "Administrative Landmarks Preservationist", "Captain D/a Deputy Chief Inspector", "Counter / Cashier", "Public Health Emergency Preparedness Specialist", "College Print Shop Associate", "Tractor Operator", "Client Service / Operations", "Taxi And Limousine Inspector", "First Asst Marine Engineer", "Front Desk Manager", "Graphic Artist", "Superintendent Of Adult Institutions", "City Attendant", "Assistance Finance Officer", "Campus Peace Officer", "Supervising Therapist", "Special Investigator", "Teacher Resource Room",
"Director Of Nursing Services", "Statistical Secretary", "Executive Director On Commission On Gender Equality", "Assistant Commissioner For Management Acd Doss", "Adult Educator Assistant Coord", "Analyst (ib/wealth)", "Assistant Media Services Technican", "Public Health Nurse", "Manager / Supervisor", "Executive Director Of The Commission On Gender Equity", "Interpreter/translator", "Valet Attendant (w/ Tips Typical Total)", "Mechanical Engineer", "Dir Of Mgnt System, Planning, Research And Eval", "Transportation Specialist", "Warden", "Administrator Supt Campus B/g", "Assistant Superintendent Of Welfare Shelters", "Director Of Community Engagement And Response", "Supervisor I",
"Forester", "College Assistant", "Assistant Corporation Counsel", "Concessions / Food Runner", "Director Of Design", "Labor Relations Analyst", "Director Of Construction", "Supervisor Elevator Mechanic", "Secretary To The Exec Deputy Commissioner", "Captain D/a Deputy Inspector", "Public Health Sanitarian", "Teacher Per Session", "Educational Administrator Uft", "Stenographic Specialist", "Store Lead", "Dir Of Home Care Services/family And Adult Services", "Expediter / Runner", "Director Of Public Health Emergency Planning", "Public Health Educator", "Counsel To The Chancellor",
"Senior School Lunch Aide", "Food Service", "Dir Policy Econom Resrch", "Usher / Box Office / Concessions", "Secretary To The Deputy Commissioner", "Director Of Intergovernmental Affairs", "Chief Administrative Law Judge", "Criminalist Assistant Director Of Laboratory", "Asist Systms Analyst", "Associate Rehabilitation Specialist", "Chief Rackets Investigator", "District Attorney", "Teller", "Department Librarian", "Publishing Associate", "Associate Landmarks Preservationist", "Special Asst For Investigations/inspector Gen", "Asphalt Plant Manager", "Stenographer To The Corporation Counsel", "Supervisor Bricklayer",
"School Lunch Assistant", "Supv Of Housing Exterminator", "Administrative Supervisor Of Building Maintenance", "Cooperative Education Trainee Engineering Aide", "Front Of House / Usher", "Captain Chief Of Intelligence", "Counter Staff", "Legal Secretarial Assistant Al 2,3,4 Only", "Supervisor Of Nurses", "Teacher Special Education", "Housing Manager", "Oiler", "Deputy City Clerk", "Director Of Plan & Field Services", "Administrative Public Health Sanitarian", "Director Of Community Programs", "High Pressure Plant Tender", "City Pest Control Aide", "Assistant Counsel", "Assistant Principal Assigned",
"Secretary To Public Administrator", "Senior Director Collections", "Police Communications Technician", "Special Assistant To The Da", "Chief Of Information Technology", "Deputy Commissioner For Administation", "Counter", "Ass Commissioner Design And Construction Management", "Inspector Boilers", "Server (restaurant)", "Director Of Photographic Services Pd", "Customer Service / Office", "Inspector Construction", "Policy Advisor To The Chancellor Ýdoe¨", "Radio Repair Mechanic", "Psychiatrist I", "Associate Executive Director", "Fiscal & Policy Analyst", "Department Manager", "Industrial Hygienist",
"Executive Assistant To The Commissioner Of Community Develop", "Deputy Director Of Construction", "Deputy Director", "Captain D/a Inspector", "Director Of Field Operations", "Director Of Cyber Crime Forensics", "Poison Information Specialist", "Associate Public Records Officer", "Administrative Public Information Specialist", "High School Student Aide", "Licensed Clinical Social Worker (lcsw)", "Customer Information Representative", "Visitor Assistant", "Director Of Independent Budget Office", "Education Facilitator", "Guest Experience Associate", "Probation Assistant", "Teacher Attendance", "Secretary To The President", "Police Officer, Special Assignment",
"Captain D/a Chief Of Management Analysis And Planning", "Child Welfare Specialist Supervisor", "City Medical Director", "Chief City Medical Examiner", "Trainer Assistant", "Chief Review Assessor", "Chief Investigator", "Deputy Chief Strategy Officer Ýdoe¨", "Staff Analyst", "Air Pollution Inspector", "Teaching Artist", "Dep Director Of Personnel & Lr", "Chair", "Fingerprint Technician Trainee", "Traffic Control Inspector", "Eoc It Assistant", "Chief Tax Compliance Officer", "Assistant Plan Examiner", "Usher / Ticket Seller", "Nycaps Process Analyst",
"Deputy Assistant Superintendent", "Director Of Puppetry", "Ticket Taker", "Eoc Lecturer", "Senior Policy Advisor To The Mayor", "Associate Fingerprint Technician", "Assistant City Highway Repairer", "Senior School Neighborhood Worker", "Special Assistant To The Commissioner", "Asst Commissioner For Policy And Community Resilience", "Executive Deputy Commissioner", "Supervisor I Social Work", "Clip Instructor", "Probation Adjunct Trainer", "Assistant Resident Building Supt", "Construction Project Manager Intern", "County Detective", "Minority Leader", "Bookseller", "Community Service Aide",
"Manager Of Park License Agreements", "Financial Clerk", "Secretary To The First Deputy Commissioner", "Director Of The Office Of Scheduling & Executive Operations", "It Associate", "It Senior Associate", "Lieutenant D/a Commander Of Detective Squad", "Chief Strategy Officer Ýdoe¨", "Retail Sales Associate", "Administrative Retirement Benefits Specialist", "Associate (ib)", "Inspector", "Assistant Housing Manager", "Hotel Manager (annual)", "Baker", "Chief Information Officer", "Asbestos Handler Supervisor", "Thermostat Repairer", "Contract Reviewer", "Supervisor Of Traffic Device Maintainers L2 & L3",
"Deputy Director Of Labor Relations", "Assistant Budget Analyst", "Executive Director And Chair, Commission On Racial Equity", "Legal Secretarial Assistant Al 1 Only", "Forensic Mortuary Technician",
]

const JobSearchDropdown: React.FC<JobSearchDropdownProps> = ({
  value,
  onChange,
  onBlur,
  placeholder = "Search or select a job role...",
  className = ""
}) => {
  const [isOpen, setIsOpen] = useState(false);
  const [searchTerm, setSearchTerm] = useState('');
  const [filteredOptions, setFilteredOptions] = useState(JOB_OPTIONS);
  const dropdownRef = useRef<HTMLDivElement>(null);
  const inputRef = useRef<HTMLInputElement>(null);

  useEffect(() => {
    const filtered = JOB_OPTIONS.filter(job =>
      job.toLowerCase().includes(searchTerm.toLowerCase())
    );
    setFilteredOptions(filtered);
  }, [searchTerm]);

  useEffect(() => {
    const handleClickOutside = (event: MouseEvent) => {
      if (dropdownRef.current && !dropdownRef.current.contains(event.target as Node)) {
        setIsOpen(false);
        setSearchTerm('');
        onBlur?.();
      }
    };

    document.addEventListener('mousedown', handleClickOutside);
    return () => document.removeEventListener('mousedown', handleClickOutside);
  }, [onBlur]);

  const handleInputChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const newValue = e.target.value;
    setSearchTerm(newValue);
    // Always update parent with the current value (including empty string)
    onChange(newValue);
    setIsOpen(true);
  };

  const handleOptionSelect = (option: string) => {
    onChange(option);
    setSearchTerm('');
    setIsOpen(false);
    onBlur?.();
  };

  const handleKeyDown = (e: React.KeyboardEvent) => {
    if (e.key === 'Enter') {
      setIsOpen(false);
      setSearchTerm('');
      onBlur?.();
    } else if (e.key === 'Escape') {
      setIsOpen(false);
      setSearchTerm('');
    }
  };

  const displayValue = searchTerm || value;

  return (
    <div ref={dropdownRef} className="relative w-full">
      <div className="relative">
        <input
          ref={inputRef}
          type="text"
          value={displayValue}
          onChange={handleInputChange}
          onFocus={() => setIsOpen(true)}
          onKeyDown={handleKeyDown}
          placeholder={placeholder}
          className={`${className} pr-8`}
        />
        <button
          type="button"
          onClick={() => {
            setIsOpen(!isOpen);
            inputRef.current?.focus();
          }}
          className="absolute right-2 top-1/2 transform -translate-y-1/2 text-app-gray-medium hover:text-app-black transition-colors"
        >
          <ChevronDown 
            className={`w-4 h-4 transition-transform duration-200 ${isOpen ? 'rotate-180' : ''}`} 
          />
        </button>
      </div>

      {isOpen && (
        <div className="absolute z-50 w-full mt-1 bg-white rounded-lg shadow-lg max-h-48 overflow-y-auto" style={{ border: '1px solid hsl(var(--app-gray-light))' }}>
          {searchTerm.length < 4 ? (
            <div className="px-3 py-2 text-app-gray-medium text-sm">
              Type at least 4 characters to search
            </div>
          ) : filteredOptions.length > 0 ? (
            filteredOptions.map((option) => (
              <button
                key={option}
                type="button"
                onClick={() => handleOptionSelect(option)}
                className="w-full px-3 py-2 text-left transition-colors text-app-black hover:bg-gray-50"
              >
                {option}
              </button>
            ))
          ) : searchTerm && !searchTerm.match(/\d/) ? (
            <button
              key="other"
              type="button"
              onClick={() => handleOptionSelect("Other")}
              className="w-full px-3 py-2 text-left transition-colors text-app-black hover:bg-gray-50"
            >
              Other
            </button>
          ) : (
            <div className="px-3 py-2 text-app-gray-medium text-sm">
              No matching jobs found
            </div>
          )}
        </div>
      )}
    </div>
  );
};

export default JobSearchDropdown;