// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hyygpxhwkvyxtbjnnpqk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh5eWdweGh3a3Z5eHRiam5ucHFrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM1NDM2ODMsImV4cCI6MjA2OTExOTY4M30.if9FMeGAPS4ke3H8orSwli-3dkHx7dE2QifGDCNTPzU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
  global: {
    headers: {
      'x-device-id': localStorage.getItem('device_id') || ''
    }
  }
});

// Update device ID header when it changes
export const updateDeviceIdHeader = (deviceId: string) => {
  console.log('🔧 Updating device_id header:', deviceId);
  // Update the global headers
  (supabase as any).headers = {
    ...(supabase as any).headers,
    'x-device-id': deviceId
  };
};