// Apply necessary plugins
plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
}

// Android configuration
android {
    namespace "com.acvetne.breakroom"
    compileSdk 35

    defaultConfig {
        applicationId 'com.acvetne.breakroom'
        minSdkVersion 23
        targetSdkVersion 35
        versionCode 2
        versionName "1.01"
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    signingConfigs {
        release {
            storeFile file("${rootDir}/../my-upload-key.jks")
            storePassword "wofwallen"
            keyAlias "my-key-alias"
            keyPassword "wofwallen"
        }
    }

    buildTypes {
        release {
            signingConfig = signingConfigs.getByName("release")
            minifyEnabled false
            shrinkResources false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }

        debug {
            minifyEnabled false
        }
    }

    kotlinOptions {
        jvmTarget = "17"
        freeCompilerArgs += ["-Xjvm-default=all"]
    }
}

dependencies {
    implementation project(':capacitor-android')
    implementation 'androidx.appcompat:appcompat:1.7.0'
    implementation 'com.google.android.material:material:1.12.0'
    implementation 'androidx.core:core-ktx:1.13.1'
    implementation 'androidx.webkit:webkit:1.8.0'
}

// Optional: Google Services plugin if google-services.json exists
def servicesJSON = file('google-services.json')
if (servicesJSON.exists() && servicesJSON.text.trim()) {
    apply plugin: 'com.google.gms.google-services'
} else {
    logger.info("google-services.json not found, Google services plugin not applied.")
}
